package service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;

import net.sf.jasperreports.engine.JasperPrint;
import play.mvc.Http;
import play.Application;

/**
 * Returns the outputstream containing report generated by the jasper report
 * 
 * @author mritunjay
 */
@SuppressWarnings("unchecked")
public interface DynamicReportService extends BaseService {
        /**
         * @param reportName
         *                   Name of the report
         * @param datas
         *                   List of beans to be populated to the report
         * @param params
         *                   Map of parameters to be passed to the JRXML
         * @param type
         *                   Type of the file
         *                   <p>
         *                   Note : Currently supporting pdf, csv, xls, rtf and html
         *                   only
         *                   </p>
         * @param request
         *                   HttpServletRequest
         * @return
         */
        public ByteArrayOutputStream generateStaticReport(String reportName, List<?> datas, Map params, String type,
                        Http.Request request);

        public ByteArrayOutputStream generateStaticReportOld(String reportName, List datas, Map params, String type,
                        Http.Request request, Application application);

        public JasperPrint getJasperPrintFromFile(String reportName, List datas, Map params, Http.Request request);

        public ByteArrayOutputStream getJasperPrintFromFileUsingJtable(String reportName, List datas, Map params,
                        String type, Http.Request request, Application application);

        public ByteArrayOutputStream getJasperPrintFromFileUsingJtable(String reportName, List idosDataSource,
                        List advAdjList, Map params, String type, Http.Request request, Application application);
}
