package com.idos.dao.balancesheet;

import javax.persistence.EntityManager;
import service.EntityManagerProvider;
import javax.persistence.EntityTransaction;

import com.idos.dao.BaseDAO;
import com.idos.util.IDOSException;
import model.balancesheet.BalanceSheetBean;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import model.Users;

public interface BalanceSheetDAO extends BaseDAO {

	/**
	 * Method - displayBalanceSheet
	 * 
	 * @param result
	 * @param json
	 * @param user
	 * @param entityManager
	 * @param entitytransaction
	 * @return
	 */
	ObjectNode displayBalanceSheet(ObjectNode result, JsonNode json, Users user, EntityManager entityManager)
			throws IDOSException;

	BalanceSheetBean populateBalanceSheetBean(JsonNode json, Users user, EntityManager entityManager)
			throws IDOSException;

	StringBuilder bsquerySB = new StringBuilder(
			"SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_COAITEMS t2 ON t2.TRANSACTION_SPECIFICS = REPLACE(t1.coa_id,'item', '') AND t2.date <= ?1 ")
			.append(" where t1.ORGANIZATION_ID = ?2 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t1.coa_id like 'item%' AND (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?3 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'item', '') ")
			.append(" and ifnull(t3.IDENT_DATA_VALID,0) not in ('8', '9', '31', '32', '33', '34', '35', '36', '37', '38') and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets")

			.append(" UNION ALL ")

			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_CASH t2 ON t2.BRANCH_DEPOSITBOX_ID = REPLACE(t1.coa_id,'cash', '') and t2.cash_type=1 and t2.date <= ?4 ")
			.append(" where t1.ORGANIZATION_ID = ?5 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_DEPOSITBOX_KEY t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?6 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cash', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")

			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_CASH t2 ON t2.BRANCH_DEPOSITBOX_ID = REPLACE(t1.coa_id,'pett', '') and t2.cash_type=2 AND t2.date <= ?7 ")
			.append(" where t1.ORGANIZATION_ID = ?8 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.PETTY_CASH_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_DEPOSITBOX_KEY t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?9 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'pett', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_BANK t2 ON t2.BRANCH_BANK_ACCOUNTSID = REPLACE(t1.coa_id,'bank', '') and t2.date <= ?10 ")
			.append(" where t1.ORGANIZATION_ID = ?11 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_BANK_ACCOUNTS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?12 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'bank', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_ADVANCE t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'vAdv', '') and t2.date <= ?13 ")
			.append(" where t1.ORGANIZATION_ID = ?14 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE_ADVANCEPAID) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?15 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'vAdv', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_ADVANCE t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'cAdv', '') and t2.date <= ?16 ")
			.append(" where t1.ORGANIZATION_ID = ?17 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500)  group by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE_ADVANCEPAID) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?18 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cAdv', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500)  group by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_CUSTOMER t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'cust', '') and t2.date <= ?19 ")
			.append(" where t1.ORGANIZATION_ID = ?20 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?21 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cust', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_CUSTOMER t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'vend', '') and t2.date <= ?22 ")
			.append(" where t1.ORGANIZATION_ID = ?23 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?24 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'vend', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'taxs', '') and t2.date <= ?25 ")
			.append(" where t1.ORGANIZATION_ID = ?26 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type = 1 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?27 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'taxs', '') ")
			.append(" and t3.tax_type = 1 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmsi', '') and t2.date <= ?28 ")
			.append(" where t1.ORGANIZATION_ID = ?29 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =30 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?30 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmsi', '') ")
			.append(" and t3.tax_type = 30 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmci', '') and t2.date <= ?31 ")
			.append(" where t1.ORGANIZATION_ID = ?32 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =31 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?33 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmci', '') ")
			.append(" and t3.tax_type = 31 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmii', '') and t2.date <= ?34 ")
			.append(" where t1.ORGANIZATION_ID = ?35 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =32 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?36 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmii', '') ")
			.append(" and t3.tax_type = 32 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmei', '') and t2.date <= ?37 ")
			.append(" where t1.ORGANIZATION_ID = ?38 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =33 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?39 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmei', '') ")
			.append(" and t3.tax_type = 33 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'taxs', '') and t2.date <= ?40 ")
			.append(" where t1.ORGANIZATION_ID = ?41 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =2 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) group by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?42 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'taxs', '') ")
			.append(" and t3.tax_type = 2 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmso', '') and t2.date <= ?43 ")
			.append(" where t1.ORGANIZATION_ID = ?44 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =50 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?45 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmso', '') ")
			.append(" and t3.tax_type = 50 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmco', '') and t2.date <= ?46 ")
			.append(" where t1.ORGANIZATION_ID = ?47 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =51 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?48 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmco', '') ")
			.append(" and t3.tax_type = 51 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmio', '') and t2.date <= ?49 ")
			.append(" where t1.ORGANIZATION_ID = ?50 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =52 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?51 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmio', '') ")
			.append(" and t3.tax_type = 52 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'rmeo', '') and t2.date <= ?52 ")
			.append(" where t1.ORGANIZATION_ID = ?53 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =53 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?54 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'rmeo', '') ")
			.append(" and t3.tax_type = 53 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'tdsi', '') and t2.tax_type = '6' and t2.date <= ?55 ")
			.append(" where t1.ORGANIZATION_ID = ?56 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?57 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='8' and t3.ID = REPLACE(t1.coa_id,'tdsi', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'192_', '') and t2.tax_type = 40 and t2.date <= ?58 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'192_', '') and t0.IDENT_DATA_VALID='31' ")
			.append(" where t1.ORGANIZATION_ID = ?59 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?60 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='31' and t3.ID = REPLACE(t1.coa_id,'192_', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")

			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194a', '') and t2.tax_type = 41 and t2.date <= ?61 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194a', '') and t0.IDENT_DATA_VALID='32' ")
			.append(" where t1.ORGANIZATION_ID = ?62 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?63 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='32' and t3.ID = REPLACE(t1.coa_id,'194a', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1941', '') and t2.tax_type = 42 and t2.date <= ?64 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1941', '') and t0.IDENT_DATA_VALID='33' ")
			.append(" where t1.ORGANIZATION_ID = ?65 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?66 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='33' and t3.ID = REPLACE(t1.coa_id,'1941', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1942', '') and t2.tax_type = 43 and t2.date <= ?67 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1942', '') and t0.IDENT_DATA_VALID='34'")
			.append(" where t1.ORGANIZATION_ID = ?68 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?69 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='34' and t3.ID = REPLACE(t1.coa_id,'1942', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194h', '') and t2.tax_type = 44 and t2.date <= ?70 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194h', '') and t0.IDENT_DATA_VALID='35' ")
			.append(" where t1.ORGANIZATION_ID = ?71 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?72 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='35' and t3.ID = REPLACE(t1.coa_id,'194h', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1943', '') and t2.tax_type = 45 and t2.date <= ?73 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1943', '') and t0.IDENT_DATA_VALID='36' ")
			.append(" where t1.ORGANIZATION_ID = ?74 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?75 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='36' and t3.ID = REPLACE(t1.coa_id,'1943', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1944', '') and t2.tax_type = 46 and t2.date <= ?76 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1944', '') and t0.IDENT_DATA_VALID='37' ")
			.append(" where t1.ORGANIZATION_ID = ?77 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?78 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='37' and t3.ID = REPLACE(t1.coa_id,'1944', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194j', '') and t2.tax_type = 47 and t2.date <= ?79 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194j', '') and t0.IDENT_DATA_VALID='38'")
			.append(" where t1.ORGANIZATION_ID = ?80 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?81 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='38' and t3.ID = REPLACE(t1.coa_id,'194j', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'sgst', '') and t2.date <= ?82 ")
			.append(" where t1.ORGANIZATION_ID = ?83 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =10 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?84 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'sgst', '') ")
			.append(" and t3.tax_type = 10 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cgst', '') and t2.date <= ?85 ")
			.append(" where t1.ORGANIZATION_ID = ?86 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =11 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?87 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cgst', '') ")
			.append(" and t3.tax_type = 11 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'igst', '') and t2.date <= ?88 ")
			.append(" where t1.ORGANIZATION_ID = ?89 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =12 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?90 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'igst', '') ")
			.append(" and t3.tax_type = 12 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cess', '') and t2.date <= ?91 ")
			.append(" where t1.ORGANIZATION_ID = ?92 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =13 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?93 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cess', '') ")
			.append(" and t3.tax_type = 13 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'sgst', '') and t2.date <= ?94 ")
			.append(" where t1.ORGANIZATION_ID = ?95 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =20 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?96 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'sgst', '') ")
			.append(" and t3.tax_type = 20 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cgst', '') and t2.date <= ?97 ")
			.append(" where t1.ORGANIZATION_ID = ?98 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =21 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?99 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cgst', '') ")
			.append(" and t3.tax_type = 21 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'igst', '') and t2.date <= ?100 ")
			.append(" where t1.ORGANIZATION_ID = ?101 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =22 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, cAssets, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?102 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'igst', '') ")
			.append(" and t3.tax_type = 22 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, cAssets, pAssets ) as t5 group by PLBSHEAD, pLiabil, cAssets, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance +cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cess', '') and t2.date <= ?103 ")
			.append(" where t1.ORGANIZATION_ID = ?104 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.tax_type =23 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, cAssets, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?105 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cess', '') ")
			.append(" and t3.tax_type = 23 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, cAssets, pAssets ) as t5 group by PLBSHEAD, pLiabil, cAssets, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_USER_ADVANCE t2 ON t2.USER_ID = REPLACE(t1.coa_id,'user', '') and t2.date <= ?106 ")
			.append(" where t1.ORGANIZATION_ID = ?107 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.TRANSACTION_PURPOSE in (15,16) and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?108 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='12' and t3.ID = REPLACE(t1.coa_id,'user', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_USER_ADVANCE t2 ON t2.USER_ID = REPLACE(t1.coa_id,'user', '') and t2.date <= ?109 ")
			.append(" where t1.ORGANIZATION_ID = ?110 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and t2.TRANSACTION_PURPOSE in (17,18) and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?111 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='13' and t3.ID = REPLACE(t1.coa_id,'user', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, sum(oBalance + cAssets), pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_INTER_BRANCH t2 ON t2.INTER_BRANCH_MAPPING_ID = REPLACE(t1.coa_id,'intb', '') and t2.DATE <= ?112 ")
			.append(" where t1.ORGANIZATION_ID = ?113 and t2.ORGNIZATION_ID = t1.ORGANIZATION_ID and t1.coa_id like 'intb%' and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, INTER_BRANCH_MAPPING t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?114 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'intb', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cLiabil ) as t5 group by PLBSHEAD, pLiabil, pAssets, cLiabil ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, sum(oBalance + cLiabil), pLiabil, cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_PAYROLL_ITEM t2 ON t2.TRANSACTION_SPECIFICS = REPLACE(t1.coa_id,'pded', '') and t2.DATE <= ?115 ")
			.append(" where t1.ORGANIZATION_ID = ?116 and t2.ORGANIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, PAYROLL_SETUP t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?117 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'pded', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets, cAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets, cAssets ");

	String bsquery = bsquerySB.toString();

	static final StringBuilder bsquerySBPrev = new StringBuilder(
			"SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_COAITEMS t2 ON t2.TRANSACTION_SPECIFICS = REPLACE(t1.coa_id,'item', '') AND t2.date <= ?1 ")
			.append(" where t1.ORGANIZATION_ID = ?2 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID AND (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?3 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'item', '') ")
			.append(" and ifnull(t3.IDENT_DATA_VALID,0) not in ('8', '9', '31', '32', '33', '34', '35', '36', '37', '38') and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets )")
			.append(" as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_CASH t2 ON t2.BRANCH_DEPOSITBOX_ID = REPLACE(t1.coa_id,'cash', '') and t2.cash_type=1 and t2.date <= ?4 ")
			.append(" where t1.ORGANIZATION_ID = ?5 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_DEPOSITBOX_KEY t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?6 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cash', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance +pLiabil), cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_CASH t2 ON t2.BRANCH_DEPOSITBOX_ID = REPLACE(t1.coa_id,'pett', '') and t2.cash_type=2 AND t2.date <= ?7 ")
			.append(" where t1.ORGANIZATION_ID = ?8 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.PETTY_CASH_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_DEPOSITBOX_KEY t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?9 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'pett', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0) - ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_BRANCH_BANK t2 ON t2.BRANCH_BANK_ACCOUNTSID = REPLACE(t1.coa_id,'bank', '') and t2.date <= ?10 ")
			.append(" where t1.ORGANIZATION_ID = ?11 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_BANK_ACCOUNTS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?12 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'bank', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_ADVANCE t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'vAdv', '') and t2.date <= ?13 ")
			.append(" where t1.ORGANIZATION_ID = ?14 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE_ADVANCEPAID) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?15 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'vAdv', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_ADVANCE t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'cAdv', '') and t2.date <= ?16 ")
			.append(" where t1.ORGANIZATION_ID = ?17 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE_ADVANCEPAID) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?18 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cAdv', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_CUSTOMER t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'cust', '') and t2.date <= ?19 ")
			.append(" where t1.ORGANIZATION_ID = ?20 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?21 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cust', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_VENDOR_CUSTOMER t2 ON t2.VENDOR_ID = REPLACE(t1.coa_id,'vend', '') and t2.date <= ?22 ")
			.append(" where t1.ORGANIZATION_ID = ?23 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.ORIGINAL_OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, VENDOR t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?24 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'vend', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'taxs', '') and t2.date <= ?25 ")
			.append(" where t1.ORGANIZATION_ID = ?26 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?27 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'taxs', '') ")
			.append(" and t3.tax_type = '1' and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'taxs', '') and t2.date <= ?28 ")
			.append(" where t1.ORGANIZATION_ID = ?29 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?30 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'taxs', '') ")
			.append(" and t3.tax_type =2 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'tdsi', '') and t2.tax_type = '6' and t2.date <= ?31 ")
			.append(" where t1.ORGANIZATION_ID = ?32 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?33 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='8' and t3.ID = REPLACE(t1.coa_id,'tdsi', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")

			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'192_', '') and t2.tax_type = '4' and t2.date <= ?34 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'192_', '') and t0.IDENT_DATA_VALID='31'")
			.append(" where t1.ORGANIZATION_ID = ?35 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?36 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='31' and t3.ID = REPLACE(t1.coa_id,'192_', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")

			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194a', '') and t2.tax_type = '4' and t2.date <= ?37 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194a', '') and t0.IDENT_DATA_VALID='32'")
			.append(" where t1.ORGANIZATION_ID = ?38 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?39 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='32' and t3.ID = REPLACE(t1.coa_id,'194a', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1941', '') and t2.tax_type = '4' and t2.date <= ?40 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1941', '') and t0.IDENT_DATA_VALID='33'")
			.append(" where t1.ORGANIZATION_ID = ?41 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?42 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='33' and t3.ID = REPLACE(t1.coa_id,'1941', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1942', '') and t2.tax_type = '4' and t2.date <= ?43 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1942', '') and t0.IDENT_DATA_VALID='34'")
			.append(" where t1.ORGANIZATION_ID = ?44 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?45 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='34' and t3.ID = REPLACE(t1.coa_id,'1942', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194h', '') and t2.tax_type = '4' and t2.date <= ?46 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194h', '') and t0.IDENT_DATA_VALID='35'")
			.append(" where t1.ORGANIZATION_ID = ?47 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?48 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='35' and t3.ID = REPLACE(t1.coa_id,'194h', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1943', '') and t2.tax_type = '4' and t2.date <= ?49 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1943', '') and t0.IDENT_DATA_VALID='36'")
			.append(" where t1.ORGANIZATION_ID = ?50 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?51 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='36' and t3.ID = REPLACE(t1.coa_id,'1943', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'1944', '') and t2.tax_type = '4' and t2.date <= ?52 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'1944', '') and t0.IDENT_DATA_VALID='37'")
			.append(" where t1.ORGANIZATION_ID = ?53 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?54 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='37' and t3.ID = REPLACE(t1.coa_id,'1944', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'194j', '') and t2.tax_type = '4' and t2.date <= ?55 ")
			.append(" left join SPECIFICS t0 on t0.ID=REPLACE(t1.coa_id,'194j', '') and t0.IDENT_DATA_VALID='38'")
			.append(" where t1.ORGANIZATION_ID = ?56 and t0.ORGANIZATION_ID=t1.ORGANIZATION_ID and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, SPECIFICS t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?57 and t3.ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.IDENT_DATA_VALID='38' and t3.ID = REPLACE(t1.coa_id,'194j', '') ")
			.append(" and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'sgst', '') and t2.date <= ?58 ")
			.append(" where t1.ORGANIZATION_ID = ?59 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?60 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'sgst', '') ")
			.append(" and t3.tax_type = 10 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cgst', '') and t2.date <= ?61 ")
			.append(" where t1.ORGANIZATION_ID = ?62 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?63 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cgst', '') ")
			.append(" and t3.tax_type = 11 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'igst', '') and t2.date <= ?64 ")
			.append(" where t1.ORGANIZATION_ID = ?65 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?66 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'igst', '') ")
			.append(" and t3.tax_type = 12 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, pLiabil, cAssets, sum(oBalance + pAssets) FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, sum(ifnull(t2.DEBIT_AMOUNT,0)-ifnull(t2.CREDIT_AMOUNT,0)) as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cess', '') and t2.date <= ?67 ")
			.append(" where t1.ORGANIZATION_ID = ?68 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?69 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cess', '') ")
			.append(" and t3.tax_type = 13 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'sgst', '') and t2.date <= ?70 ")
			.append(" where t1.ORGANIZATION_ID = ?71 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?72 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'sgst', '') ")
			.append(" and t3.tax_type =20 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cgst', '') and t2.date <= ?73 ")
			.append(" where t1.ORGANIZATION_ID = ?74 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?75 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cgst', '') ")
			.append(" and t3.tax_type =21 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'igst', '') and t2.date <= ?76 ")
			.append(" where t1.ORGANIZATION_ID = ?77 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?78 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'igst', '') ")
			.append(" and t3.tax_type =22 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ")

			.append(" UNION ALL ")
			.append("SELECT PLBSHEAD, cLiabil, sum(oBalance + pLiabil), cAssets, pAssets FROM ")
			.append("( SELECT t1.PLBSHEAD, 0 as cLiabil, sum(ifnull(t2.CREDIT_AMOUNT,0)-ifnull(t2.DEBIT_AMOUNT,0)) as pLiabil, 0 as cAssets, 0 as pAssets, 0 as oBalance ")
			.append(" FROM PLBSCOAMAP t1 left join TRIALBALANCE_TAXES t2 ON t2.BRANCH_TAXESID = REPLACE(t1.coa_id,'cess', '') and t2.date <= ?79 ")
			.append(" where t1.ORGANIZATION_ID = ?80 and t2.BRANCH_ORGNIZATION_ID = t1.ORGANIZATION_ID and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ")
			.append(" UNION ALL ")
			.append(" select t1.PLBSHEAD, 0 as cLiabil, 0 as pLiabil, 0 as cAssets, 0 as pAssets, sum(t3.OPENING_BALANCE) as oBalance from PLBSCOAMAP t1, BRANCH_TAXES t3 ")
			.append(" WHERE t1.ORGANIZATION_ID = ?81 and t3.BRANCH_ORGANIZATION_ID = t1.ORGANIZATION_ID and t3.ID = REPLACE(t1.coa_id,'cess', '') ")
			.append(" and t3.tax_type =23 and (t1.PLBSHEAD >=300 and t1.PLBSHEAD < 500) GROUP by t1.PLBSHEAD, pLiabil, pAssets ) as t5 group by PLBSHEAD, pLiabil, pAssets ");

	static final String bsqueryPrev = bsquerySBPrev.toString();
}
