CREATE TABLE `bom` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime NOT NULL,
  `CREATED_BY` int(32) NOT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) DEFAULT '1',
  `ORGANIZATION_ID` int(32) NOT NULL,
  `BOM_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
KEY `fk_BOM_CREATED` (`CREATED_BY`),
  KEY `fk_BOM_MODIFIED` (`MODIFIED_BY`),
  KEY `fk_BOM_ORG` (`ORGANIZATION_ID`),
  CONSTRAINT `fk_BOM_CREATED` FOREIGN KEY (`CREATED_BY`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_BOM_MODIFIED` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_BOM_ORG` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `organization` (`id`)

  
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;