CREATE TABLE `bom_items` (
  `ID` bigint(255) NOT NULL AUTO_INCREMENT,
`CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) DEFAULT '1',
  `BOM_ID` bigint(255) DEFAULT NULL,
  `EXPENSE_ID` int(255) DEFAULT null,
  `NO_OF_UNITS` int(32) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_BOM_ITEM_CREATED` (`CREATED_BY`),
  KEY `fk_BOM_ITEM_MODIFIED` (`MODIFIED_BY`),
  KEY `fk_BOM_ITEM_BOM` (`BOM_ID`),
  
  CONSTRAINT `fk_BOM_ITEM_BOM` FOREIGN KEY (`BOM_ID`) REFERENCES `bom` (`id`)
  
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;