


ALTER TABLE TRANSACTION_ITEMS add COLUMN NO_OF_UNITS_RETURNED bigint(20) DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN GROSS_AMOUNT_RETURNED double DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN ADV_ADJUSTMENT_RETURNED double DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN TOTAL_TAX_RETURNED double DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN NET_AMOUNT_RETURNED double DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN AVAILABLE_ADVANCE_FOR_RETURNED double DEFAULT '0';
ALTER TABLE TRANSACTION_ITEMS add COLUMN TAX_DESCRIPTION_RETURNED text DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS add COLUMN WITHHOLDING_AMOUNT_RETURNED double DEFAULT '0';


alter table ORGANIZATION add column GST_COUNTRY_CODE varchar(10) default null;

alter table BRANCH add column BRANCH_ADDRESS varchar(250) default null;
alter table BRANCH add column STATE_CODE varchar(10) default null;
alter table BRANCH add column GSTIN varchar(15) default null;

alter table BRANCH_SPECIFICS_TAX_FORMULA add column GST_ITEM_CATEGORY varchar(15) default null;
alter table BRANCH_SPECIFICS_TAX_FORMULA add column GST_ITEM_CODE varchar(50) default null;
alter table BRANCH_SPECIFICS_TAX_FORMULA add column GST_TAX_RATE double DEFAULT NULL;

ALTER TABLE SPECIFICS add COLUMN GST_ITEM_CATEGORY varchar (50) DEFAULT NULL;
ALTER TABLE SPECIFICS add COLUMN GST_ITEM_CODE varchar(50) DEFAULT NULL;
ALTER TABLE SPECIFICS add COLUMN GST_TYPE_OF_SUPPLY varchar (50) DEFAULT NULL;
ALTER TABLE SPECIFICS add COLUMN GST_TAX_RATE double DEFAULT '0';

CREATE TABLE GST_SERVICES_CODES (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime NOT NULL,
  CREATED_BY int(32) NOT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,  
  GROUP_ID int(32) NOT NULL,   
  SERVICE_CODE VARCHAR(100) NOT NULL,
  SERVICE_DESCRIPTION varchar(1000) NOT NULL,
  TAX_RATE double DEFAULT 0,
  GST_COUNTRY_CODE varchar(10) DEFAULT NULL, 
  PRIMARY KEY (ID)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GST_GOODS_CODES (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime NOT NULL,
  CREATED_BY int(32) NOT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,  
  GROUP_ID int(32) NOT NULL,   
  GOODS_CODE VARCHAR(100) NOT NULL,
  GOODS_DESCRIPTION VARCHAR(1000) NOT NULL,
  TAX_RATE double DEFAULT 0,
  GST_COUNTRY_CODE varchar(10) DEFAULT NULL,
--   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

//GST Customer GSTN

ALTER TABLE VENDOR add COLUMN GSTIN varchar(15) DEFAULT NULL;
ALTER TABLE VENDOR add COLUMN IS_BUSINESS int(2) DEFAULT 0;
ALTER TABLE VENDOR add COLUMN IS_REGISTERED int(2) DEFAULT 0;

drop  TABLE CUSTOMER_GSTIN_DETAIL;

ALTER TABLE CUSTOMER_DETAIL drop foreign key fk_CUSTOMER_DETAIL_BRANCH_ORG;
ALTER TABLE CUSTOMER_DETAIL drop key fk_CUSTOMER_DETAIL_BRANCH_ORG;
ALTER TABLE CUSTOMER_DETAIL drop column BRANCH_ID;

ALTER TABLE CUSTOMER_DETAIL ADD CONSTRAINT fk_CUSTOMER_DETAIL_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID);
ALTER TABLE `CUSTOMER_DETAIL` ADD GSTIN varchar(15) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD SHIPPING_STATE_CODE varchar(15) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_ADDRESS varchar(750) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_COUNTRY int(3) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_STATE varchar(256) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_LOCATION varchar(256) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_EMAIL varchar(256) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_PHONE_COUNTRY_CODE varchar(256) DEFAULT NULL;
ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_PHONE varchar(50) DEFAULT NULL;
alter table CUSTOMER_DETAIL ADD SHIPPING_STATE varchar(256) DEFAULT NULL;
create index idx_CUSTOMER_DETAIL_GSTIN on `CUSTOMER_DETAIL` (GSTIN);
alter table VENDOR ADD COUNTRY_STATE varchar(256) DEFAULT NULL;

ALTER TABLE `TRANSACTION` ADD `SOURCE_GSTIN` VARCHAR(20) DEFAULT NULL;
ALTER TABLE `TRANSACTION` ADD `DESTINATION_GSTIN` VARCHAR(20) DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS ADD TAXABLE_AMOUNT double DEFAULT NULL;

----------------End R170701-----------------

ALTER TABLE BRANCH_TAXES MODIFY COLUMN TAX_TYPE INT(2) DEFAULT 0;


CREATE TABLE `VENDOR_DETAIL` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `VENDOR_ID` bigint(50) NOT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `GSTIN` varchar(15) DEFAULT NULL,
  `ADDRESS` varchar(750) NOT NULL,
  `LOCATION` varchar(256) DEFAULT NULL,
  `COUNTRY_STATE` varchar(256) DEFAULT NULL,
  `COUNTRY` int(32) DEFAULT NULL,
  `PHONE_COUNTRY_CODE` varchar(256) DEFAULT NULL,
  `PHONE` varchar(256) DEFAULT NULL,
  `STATE_CODE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_VENDOR_DETAIL_CREATEDBY` (`CREATED_BY`),
  KEY `fk_VENDOR_DETAIL_MODIFIEDBY` (`MODIFIED_BY`),
  KEY `fk_VENDOR_DETAIL_VENDOR_ID` (`VENDOR_ID`),
  KEY `fk_VENDOR_DETAIL_ORG` (`ORGANIZATION_ID`),
  KEY `idx_VENDOR_DETAIL_GSTIN` (`GSTIN`),
  CONSTRAINT `fk_VENDOR_DETAIL_CREATEDBY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDOR_DETAIL_MODIFIEDBY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDOR_DETAIL_VENDOR_ID` FOREIGN KEY (`VENDOR_ID`) REFERENCES `VENDOR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDOR_DETAIL_ORG` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


ALTER TABLE ORGANIZATION add COLUMN PURCHASE_ORDER_SERIAL int(32) DEFAULT '0';
ALTER TABLE ORGANIZATION add COLUMN OFF_PURCHASEORDER_SERIAL int(32) DEFAULT '0';

alter table TRANSACTION_ITEMS add column PRICE_PER_UNIT_RETURNED double DEFAULT NULL;

alter table TRANSACTION_ITEMS add column ADVADJ_TAX1_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX2_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX3_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX4_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX5_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX6_VALUE double DEFAULT NULL;
alter table TRANSACTION_ITEMS add column ADVADJ_TAX7_VALUE double DEFAULT NULL;

ALTER TABLE TRANSACTION_ITEMS drop column TAXABLE_AMOUNT;
ALTER TABLE TRANSACTION_ITEMS ADD INVOICE_VALUE double DEFAULT NULL;
ALTER TABLE TRANSACTION ADD TYPE_OF_SUPPLY int DEFAULT 0;
ALTER TABLE TRANSACTION ADD WALKIN_CUSTOMER_TYPE int DEFAULT 0;

CREATE TABLE `CUSTOMER_WALKIN_DETAIL` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `GSTIN` varchar(15) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(750) NOT NULL,
  `SHIPPING_ADDRESS` varchar(750) NOT NULL,
  `SHIPPING_COUNTRY` int(32) DEFAULT NULL,
  `SHIPPING_STATE` varchar(256) DEFAULT NULL,
  `SHIPPING_STATE_CODE` varchar(15) DEFAULT NULL,
  `SHIPPING_LOCATION` varchar(256) DEFAULT NULL,
  `SHIPPING_PHONE_COUNTRY_CODE` varchar(256) DEFAULT NULL,
  `SHIPPING_PHONE` varchar(256) DEFAULT NULL,
  `BILLING_ADDRESS` varchar(750) DEFAULT NULL,
  `BILLING_COUNTRY` int(3) DEFAULT NULL,
  `BILLING_STATE` varchar(256) DEFAULT NULL,
  `BILLING_LOCATION` varchar(256) DEFAULT NULL,
  `BILLING_EMAIL` varchar(256) DEFAULT NULL,
  `BILLING_PHONE_COUNTRY_CODE` varchar(256) DEFAULT NULL,
  `BILLING_PHONE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_CUSTOMER_WALKIN_DETAIL_CREATEDBY` (`CREATED_BY`),
  KEY `fk_CUSTOMER_WALKIN_DETAIL_MODIFIEDBY` (`MODIFIED_BY`),
  KEY `fk_CUSTOMER_WALKIN_DETAIL_ORG` (`ORGANIZATION_ID`),
  KEY `idx_CUSTOMER_WALKIN_DETAIL_GSTIN` (`GSTIN`),
  CONSTRAINT `fk_CUSTOMER_WALKIN_DETAIL_CREATEDBY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMER_WALKIN_DETAIL_MODIFIEDBY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMER_WALKIN_DETAIL_ORG` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE KAIZALA_GROUPS (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(11) DEFAULT NULL,
   GROUP_ID text,
  `ASSIGNED_TO_PHONE_NUMBER` text,
  PO_GENERATOR_PHONE_NUMBER text,
   PRIMARY KEY (`ID`)
  );

----------------End R170801-----------------
alter table TRANSACTION_ITEMS add ADVANCE_PURPOSE varchar(256) default null;
----------------End R170802-----------------
alter table TRANSACTION_ITEMS add ADVANCE_ADJ_TRANS_LIST varchar(512) default null;


ALTER TABLE TRANSACTION ADD WITH_WITHOUT_TAX int DEFAULT 0;

ALTER TABLE USERS ADD failed_attempt int DEFAULT 0;

DROP TABLE `TRANSACTION_INVOICE`;
CREATE TABLE `TRANSACTION_INVOICE` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `BRANCH_ID` int(32)  DEFAULT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `TRANSACTION_ID` bigint(50) NOT NULL,
  `CUSTOMER_ID` bigint(50) DEFAULT NULL,
  `INVOICE_NUMBER` varchar(50) NOT NULL,
  `TRANSPORTATION_MODE` varchar(50) DEFAULT NULL,
  `VEHICLE_DETAIL` VARCHAR(750) DEFAULT NULL,
  `DOS_TIME` datetime DEFAULT NULL,
  `TERMS` VARCHAR(750) DEFAULT NULL,
  `COUNTRY_NAME` VARCHAR(256) DEFAULT NULL,
  `CURRENCY_CODE` VARCHAR(50) DEFAULT NULL,
  `CUR_CONV_RATE` double DEFAULT 0,
  `DATE_REMOVAL_GOODS` datetime DEFAULT NULL,
  `APPL_NUM_GOODS_REMOVAL` varchar(256) DEFAULT NULL,
  `GSTIN_ECOM_OPERATOR` varchar(50) DEFAULT NULL,
  `FILE_NAME` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TRANSACTION_INVOICE_BRANCH_ORG` FOREIGN KEY (`BRANCH_ID`, `ORGANIZATION_ID`) REFERENCES `BRANCH` (`ID`, `ORGANIZATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_INVOICE_CREATEDBY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_INVOICE_MODIFIEDBY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_INVOICE_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `VENDOR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTION_INVOICE_TRANSACTION_ID` FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `TRANSACTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8;

CREATE TABLE `ADVANCE_ADJUSTMENT_DETAIL`(
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `BRANCHID` int(32)  DEFAULT NULL,
  `ORGANIZATIONID` int(32) NOT NULL,
  `TRANSACTIONID` bigint(50) NOT NULL,
  `ADV_TRANSACTIONID` bigint(50) NOT NULL,
  `ADJUSTED_AMOUNT` double DEFAULT 0,
  ADVADJ_TAX1_VALUE double DEFAULT 0,
  ADVADJ_TAX2_VALUE double DEFAULT 0,
  ADVADJ_TAX3_VALUE double DEFAULT 0,
  ADVADJ_TAX4_VALUE double DEFAULT 0,
  ADVADJ_TAX5_VALUE double DEFAULT 0,
  ADVADJ_TAX6_VALUE double DEFAULT 0,
  ADVADJ_TAX7_VALUE double DEFAULT 0,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_ADVANCE_ADJUSTMENT_DETAIL_BRANCH_ORG` FOREIGN KEY (`BRANCHID`, `ORGANIZATIONID`) REFERENCES `BRANCH` (`ID`, `ORGANIZATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVANCE_ADJUSTMENT_DETAIL_CREATEDBY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVANCE_ADJUSTMENT_DETAIL_MODIFIEDBY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVANCE_ADJUSTMENT_DETAIL_ADV_TRANSID` FOREIGN KEY (`ADV_TRANSACTIONID`) REFERENCES `TRANSACTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADVANCE_ADJUSTMENT_DETAIL_TRANSID` FOREIGN KEY (`TRANSACTIONID`) REFERENCES `TRANSACTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8;

CREATE TABLE SPECIFICS_COMBINATION_SALES (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,  
  SPECIFICS_ID bigint(50) DEFAULT NULL,
  COMB_SPECIFICS_ID bigint(50) DEFAULT NULL,  
  ORGANIZATION_ID int(32) DEFAULT NULL,
  OPENING_BALANCE_UNITS int(32) DEFAULT NULL,
  OPENING_BALANCE_RATE double DEFAULT NULL,
  PRIMARY KEY (ID)  
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

alter table SPECIFICS add IS_COMBINATION_SALES int(1) DEFAULT '0';

alter table VENDOR add CREDIT_LIMIT double DEFAULT '0';
alter table VENDOR add EXCEEDING_CREDIT_PROCESS_STOP int(1) DEFAULT '0';

----------------End ---170901-----------------
alter table TRANSACTION_ITEMS add column TAX1_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX2_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX3_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX4_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX5_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX6_ID int(32) default null;
alter table TRANSACTION_ITEMS add column TAX7_ID int(32) default null;
----------------End ---170903-----------------
alter table VENDOR add EXCLUDE_ADVANCE_FROM_CREDIT_LIMIT int(1) DEFAULT '0';
----------------End ---170904-----------------
alter table TRANSACTION_INVOICE MODIFY COLUMN COUNTRY_NAME  varchar(50) DEFAULT 0;
alter table BRANCH_SPECIFICS_TAX_FORMULA add VENDOR_TYPE int(1) DEFAULT NULL;
alter table BRANCH_SPECIFICS_TAX_FORMULA add VENDOR_ID bigint(50) DEFAULT NULL;
alter table BRANCH_SPECIFICS_TAX_FORMULA add HSN_DESC VARCHAR(256) DEFAULT NULL;
alter table BRANCH_SPECIFICS_TAX_FORMULA add constraint `fk_BRANCH_SPECIFICS_TAX_FORMULA_VENDOR` foreign key (`VENDOR_ID`) references `VENDOR` (`ID`);

ALTER TABLE `CUSTOMER_DETAIL` ADD BILLING_STATE_CODE varchar(15) DEFAULT NULL;

ALTER TABLE TRANSACTION_INVOICE ADD INV_REF_DATE datetime DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD INV_REF_NO varchar(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD GRN_DATE datetime DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD GRN_REF_NO varchar(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD IMPORT_DATE datetime DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD IMPORT_REF_NO varchar(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_INVOICE ADD AMOUNT  double DEFAULT '0';

CREATE TABLE LOG_STORED_PROC (
  ID int(32) NOT NULL AUTO_INCREMENT,
  MESSAGE varchar(1000),
  NAME varchar(200),
  PRIMARY KEY (ID));

  CREATE TABLE GST_FILING (
  `ID` int(32) NOT NULL AUTO_INCREMENT,
  `TRANSACTION_ID` int(32) NOT NULL DEFAULT '0',
  `BRANCH_ID` int(32) DEFAULT NULL,
  `ORGANIZATION_ID` int(32) DEFAULT NULL,
  `TRANSACTION_DATE` date DEFAULT NULL,
  `TRANSACTION_PURPOSE` int(11) DEFAULT NULL,
  `GST_FILING_STATUS` int(2) DEFAULT '0',
  `GST_AGENT_NAME` varchar(200) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL,
  `CREATED_BY` int(32) NOT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
----------------End ---1701102-----------------
alter table CUSTOMER_DETAIL MODIFY COLUMN SHIPPING_ADDRESS  varchar(750) DEFAULT NULL;
alter table TRIALBALANCE_TAXES add `TRANSACTION_SPECIFICS` bigint(50) DEFAULT NULL;
alter table TRIALBALANCE_TAXES add `TRANSACTION_SPECIFICS_PARTICULARS` bigint(50) DEFAULT NULL;
alter table PROVISION_JOURNAL_ENTRY_DETAIL add column BRANCH_ID  int(32) DEFAULT NULL;
alter table PROVISION_JOURNAL_ENTRY_DETAIL add column ORGANIZATION_ID int(32) DEFAULT 0;
alter table USERS add MODULE_RIGHTS varchar(20) default '00000000000000000000';
----------------End ---1701201-----------------
alter table BRANCH_has_SPECIFICS add column OPENING_BALANCE double default null;
alter table BRANCH_has_SPECIFICS add column INV_OPENING_BALANCE_UNITS double default null;
alter table BRANCH_has_SPECIFICS add column INV_OPENING_BALANCE_RATE double default null;
alter table BRANCH_has_SPECIFICS add column INV_OPENING_BALANCE double default null;

alter table BRANCH_has_VENDORS add column ORIGINAL_OPENING_BALANCE double default null;
alter table BRANCH_has_VENDORS add column OPENING_BALANCE double default null;
alter table BRANCH_has_VENDORS add column OPENING_BALANCE_ADVANCEPAID double default null;
alter table BRANCH_has_VENDORS add column ORIGINAL_OPENING_BALANCE_ADVANCEPAID double default null;

alter table VENDOR add column CUSTOMER_CODE varchar(100) default null;

DROP TABLE rec_pay_seq;
CREATE TABLE rec_pay_seq(
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `temp_rec_payment_trans` (
  `TRAN_SER_NO` varchar(50) DEFAULT NULL,
  `TRANS_DATE` varchar(50) DEFAULT NULL,
  `BRANCH_NAME` varchar(100) DEFAULT NULL,
  `CUST_ID` varchar(100) DEFAULT NULL,
  `INV_ID` varchar(200) DEFAULT NULL,
  `PAYMENT_REC` varchar(100) DEFAULT NULL,
  `TAX_WITHHELD` varchar(100) DEFAULT NULL,
  `RECEIPT_TYPE` varchar(50) DEFAULT NULL,
  `BANK_DETAILS` varchar(100) DEFAULT NULL,
  `INSTRUMENT_NO` varchar(50) DEFAULT NULL,
  `INSTRUMENT_DATE` varchar(50) DEFAULT NULL,
  `RECEIPT_DETAILS` varchar(50) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE sell_on_credit_seq;
CREATE TABLE  sell_on_credit_seq (
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (30,null,null,null,null,1,'Credit Note for customer','What',1);
insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (31,null,null,null,null,1,'Debit Note for customer','What',1);
insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (32,null,null,null,null,1,'Credit Note for vendor','What',1);
insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (33,null,null,null,null,1,'Debit Note for vendor','What',1);

ALTER TABLE `TRANSACTION` ADD `LINKED_TXN_REF` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `TRANSACTION` ADD `CDTDBT_INCREASE_DECREASE` int(1) DEFAULT NULL;

CREATE TABLE `temp_sell_on_credit_trans` (
  `TRAN_SER_NO` varchar(50) DEFAULT NULL,
  `TRANS_DATE` varchar(50) DEFAULT NULL,
  `BRANCH_NAME` varchar(100) DEFAULT NULL,
  `PROJECT_NAME` varchar(100) DEFAULT NULL,
  `TYPE_OF_SUPPLY` varchar(100) DEFAULT NULL,
  `withORWithoutGST` varchar(100) DEFAULT NULL,
  `CUST_ID` varchar(50) DEFAULT NULL,
  `PO_REFERENCE` varchar(50) DEFAULT NULL,
  `ITEM_CODE` varchar(100) DEFAULT NULL,
  `PRICE` varchar(100) DEFAULT NULL,
  `UNITS` varchar(100) DEFAULT NULL,
  `DISCOUNT`  varchar(100) DEFAULT NULL,
  `ADVANCE_ADJUSTMENT` varchar(100) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8;
 
CREATE TABLE sell_on_cash_seq (
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE TABLE `temp_sell_on_cash_trans` (
  `TRAN_SER_NO` varchar(50) DEFAULT NULL,
  `TRANS_DATE` varchar(50) DEFAULT NULL,
  `BRANCH_NAME` varchar(250) DEFAULT NULL,
  `PROJECT_NAME` varchar(250) DEFAULT NULL,
  `TYPE_OF_SUPPLY` varchar(50) DEFAULT NULL,
  `withORWithoutGST` varchar(50) DEFAULT NULL,
  `CUST_ID` varchar(50) DEFAULT NULL,
  `PO_REFERENCE` varchar(250) DEFAULT NULL,
  `ITEM_CODE` varchar(100) DEFAULT NULL,
 
  `PRICE` varchar(100) DEFAULT NULL,
  `UNITS` varchar(100) DEFAULT NULL,
  `DISCOUNT`  varchar(100) DEFAULT NULL,
  `ADVANCE_ADJUSTMENT` varchar(100) DEFAULT NULL,
  `RECEIPT_TYPE` varchar(50) DEFAULT NULL,
  `BANK_DETAILS` varchar(100) DEFAULT NULL,
  `INSTRUMENT_NO` varchar(100) DEFAULT NULL,
  `INSTRUMENT_DATE` varchar(50) DEFAULT NULL,
  `RECEIPT_DETAILS` varchar(100) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



alter table USERS add TRANSACTION_CREATION_COAINCOME mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAINCOME_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAINCOME_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_CREATION_COAEXPENSE mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAEXPENSE_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAEXPENSE_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_CREATION_COAASSET mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAASSET_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COAASSET_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_CREATION_COALIABL mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COALIABL_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_CREATION_COALIABL_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_APPROVAL_COAINCOME mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAINCOME_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAINCOME_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_APPROVAL_COAEXPENSE mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAEXPENSE_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAEXPENSE_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_APPROVAL_COAASSET mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAASSET_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COAASSET_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_APPROVAL_COALIABL mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COALIABL_FROM_AMOUNT mediumtext default null;
alter table USERS add TRANSACTION_APPROVAL_COALIABL_TO_AMOUNT mediumtext default null;

alter table USERS add TRANSACTION_AUDITOR_COAINCOME mediumtext default null;
alter table USERS add TRANSACTION_AUDITOR_COAEXPENSE mediumtext default null;
alter table USERS add TRANSACTION_AUDITOR_COAASSET mediumtext default null;
alter table USERS add TRANSACTION_AUDITOR_COALIABL mediumtext default null;

----------------End ---180201-----------------
alter table TRADING_INVENTORY add TRANSACTION_GROSS double default null;
alter table SPECIFICS add IS_PRICE_INCLUSIVE int(1) default 0;
alter table USERS add column karvy_password varchar(250) default null;

alter table PROVISION_JOURNAL_ENTRY_DETAIL add UNITS double default null;
alter table PROVISION_JOURNAL_ENTRY_DETAIL add PRICE double default null;
alter table PROVISION_JOURNAL_ENTRY_DETAIL add PROJECT_ID int(32) default null;
ALTER TABLE PROVISION_JOURNAL_ENTRY_DETAIL ADD CONSTRAINT fk_PROVISION_JOURNAL_ENTRY_DETAIL_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID);

alter table ORGANIZATION add IS_COMPOSITION_SCHEME int(1) default 0;
alter table TRANSACTION_ITEMS add BRANCH_SPECIFICS_TAX_FORMULA_ID int(32) default null;

CREATE TABLE `TRIALBALANCE_INTER_BRANCH` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `ORGNIZATION_ID` int(32) DEFAULT NULL,
  `FROM_BRANCH_ID` int(32) DEFAULT NULL,
  `TO_BRANCH_ID` int(32) DEFAULT NULL,
  `TRANSACTION_ID` bigint(50) DEFAULT NULL,
  `TRANSACTION_PURPOSE` int(32) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `CREDIT_AMOUNT` double DEFAULT NULL,
  `DEBIT_AMOUNT` double DEFAULT NULL,
  `CLOSING_BALANCE` double DEFAULT NULL,
   `TYPE_IDENTIFIER` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `TRANSACTION` CHANGE `CDTDBT_INCREASE_DECREASE` `TYPE_IDENTIFIER` int(1) DEFAULT NULL;

DROP TABLE buy_on_credit_seq;
CREATE TABLE  buy_on_credit_seq (
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `temp_buy_on_credit_trans` (
  `TRAN_SER_NO` varchar(250) DEFAULT NULL,
  `TRANS_DATE` varchar(250) DEFAULT NULL,
  `BRANCH_NAME` varchar(250) DEFAULT NULL,
  `PROJECT_NAME` varchar(250) DEFAULT NULL,
  `TYPE_OF_SUPPLY` varchar(250) DEFAULT NULL,
 
  `CUST_ID` varchar(250) DEFAULT NULL,
  `PO_REFERENCE` varchar(250) DEFAULT NULL,
  `ITEM_CODE` varchar(250) DEFAULT NULL,
  `PRICE` varchar(250) DEFAULT NULL,
  `UNITS` varchar(250) DEFAULT NULL,
  `GST RATE` varchar(250) DEFAULT NULL,
  `CESS RATE` varchar(250) DEFAULT NULL,
  `ADVANCE_ADJUSTMENT` varchar(250) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL,
  `INVOICE_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `INVOICE_REFEREVCE_NUMBER` varchar(250) DEFAULT NULL,
  `DC_GRN_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `DC_GRN_REFERENCE_NUMBER` varchar(250) DEFAULT NULL,
  `WAY_BILL_NO` varchar(250) DEFAULT NULL,
  `TRANPORTER_NAME` varchar(250) DEFAULT NULL,
  `LORRY_RECEIPT_NUMBER` varchar(250) DEFAULT NULL,
  `LORRY_RECEIPT_DATE` varchar(250) DEFAULT NULL,
  `IMPORT_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `IMPORT_REFERENCE_NUMBER` varchar(250) DEFAULT NULL,
   `PORT_CODE` varchar(250) DEFAULT NULL
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

drop table PAYROLL_SETUP;
CREATE TABLE PAYROLL_SETUP (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  PAYROLL_TYPE int(1),
  PAYROLL_HEAD_NAME varchar(256) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8;


drop table PAYROLL_USERS_DATA;
CREATE TABLE PAYROLL_USERS_DATA (
  ID int(32) NOT NULL AUTO_INCREMENT,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) NOT NULL,
  PAYROLL_SETUP_ID int(32) NOT NULL,
  ANNUAL_INCOME double,
  MONTHLY_INCOME double,  
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  PAYROLL_TYPE int(1),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table PAYROLL_USER_PAYSLIP;
CREATE TABLE PAYROLL_USER_PAYSLIP (
  ID int(32) NOT NULL AUTO_INCREMENT,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) NOT NULL,
  PAYSLIP_YEAR int(7) NOT NULL,
  PAYSLIP_MONTH mediumtext NOT NULL,
  INCOME1 double,
  INCOME2 double,
  INCOME3 double,
  INCOME4 double,
  INCOME5 double,
  INCOME6 double,
  INCOME7 double,
  DEDUCTION1 double,
  DEDUCTION2 double,
  DEDUCTION3 double,
  DEDUCTION4 double,
  DEDUCTION5 double,
  DEDUCTION6 double,
  DEDUCTION7 double,
  TOTAL_INCOME double,  
  TOTAL_DEDUCTION double,  

  NET_PAY double,
  PAYMENT_MODE int(1),   
  INSTRUMENT_NUMBER varchar(50) DEFAULT NULL,
  INSTRUMENT_DATE varchar(50) DEFAULT NULL,
  RECEIPT_DETAILS varchar(50) DEFAULT NULL,
  TRANSACTION_BRANCH_BANK bigint(50) DEFAULT NULL,

  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE buy_on_cash_seq;
CREATE TABLE  buy_on_cash_seq (
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `temp_buy_on_cash_trans` (
  `TRAN_SER_NO` varchar(250) DEFAULT NULL,
  `TRANS_DATE` varchar(250) DEFAULT NULL,
  `BRANCH_NAME` varchar(250) DEFAULT NULL,
  `PROJECT_NAME` varchar(250) DEFAULT NULL,
  `TYPE_OF_SUPPLY` varchar(250) DEFAULT NULL,
  
  `CUST_ID` varchar(250) DEFAULT NULL,
  `PO_REFERENCE` varchar(250) DEFAULT NULL,
  `ITEM_CODE` varchar(250) DEFAULT NULL,
  `PRICE` varchar(250) DEFAULT NULL,
  `UNITS` varchar(250) DEFAULT NULL,
  `GST RATE` varchar(250) DEFAULT NULL,
  `CESS RATE` varchar(250) DEFAULT NULL,
  `ADVANCE_ADJUSTMENT` varchar(250) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL,
  `INVOICE_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `INVOICE_REFEREVCE_NUMBER` varchar(250) DEFAULT NULL,
  `DC_GRN_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `DC_GRN_REFERENCE_NUMBER` varchar(250) DEFAULT NULL,
  `WAY_BILL_NO` varchar(250) DEFAULT NULL,
  `TRANPORTER_NAME` varchar(250) DEFAULT NULL,
  `LORRY_RECEIPT_NUMBER` varchar(250) DEFAULT NULL,
  `LORRY_RECEIPT_DATE` varchar(250) DEFAULT NULL,
  `IMPORT_REFERENCE_DATE` varchar(250) DEFAULT NULL,
  `IMPORT_REFERENCE_NUMBER` varchar(250) DEFAULT NULL,
   `PORT_CODE` varchar(250) DEFAULT NULL,
   `RECEIPT_TYPE` varchar(50) DEFAULT NULL,
  `BANK_DETAILS` varchar(100) DEFAULT NULL,
  `INSTRUMENT_NO` varchar(100) DEFAULT NULL,
  `INSTRUMENT_DATE` varchar(50) DEFAULT NULL,
  `RECEIPT_DETAILS` varchar(100) DEFAULT NULL
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

alter table ORGANIZATION add PLACE_OF_SUPPLY_TYPE int(1) default 1;
alter table ORGANIZATION add ADVANCE_RECEIPT_SERIAL int(32) default 0;
alter table ORGANIZATION add ADVANCE_RECEIPT_INTERVAL int(1) default null;
alter table ORGANIZATION add DEBIT_NOTE_CUST_SERIAL int(32) default 0;
alter table ORGANIZATION add DEBIT_NOTE_CUST_INTERVAL int(1) default null;
alter table ORGANIZATION add CREDIT_NOTE_CUST_SERIAL int(32) default 0;
alter table ORGANIZATION add CREDIT_NOTE_CUST_INTERVAL int(1) default null;
alter table ORGANIZATION add PURCHASE_ORDER_INTERVAL int(1) default null;
alter table ORGANIZATION add ORG_SERIAL_GENRATION_TYPE int(32) default 1;

CREATE TABLE `ORGANIZATION_GSTIN_SERIALS` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `GSTIN` varchar(15) NOT NULL,
  `SERIAL_NO` int(32) DEFAULT 0,
  `DOC_CAT_NO` int(32) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_ORGANIZATION_GST_SERIALS_ORG` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

alter table VENDOR_has_SPECIFICS add column BRANCH_SPECIFICS_TAX_FORMULA_ID int(32) default null;

alter table ORGANIZATION add GSTIN_INTERVAL int(1) default 1;
alter table ORGANIZATION add SERIAL_CURRENT_MONTH int(32) default 3; 
alter table ORGANIZATION add SERIAL_YEAR_CHANGED_DATE datetime default NULL;

update TRANSACTION_PURPOSE set PRESENT_STATUS = 0 where ID in (12,13);
update USER_TRANSACTION_PURPOSE set PRESENT_STATUS = 0 where TRANSACTION_PURPOSE_ID in (12,13);


alter table PROVISION_JOURNAL_ENTRY_DETAIL add column `HEAD_ID2` bigint(50) DEFAULT NULL;

CREATE TABLE CLAIM_DETAILS (
	 ID bigint(50) NOT NULL AUTO_INCREMENT,
	 CREATED_AT datetime DEFAULT NULL,
	 CREATED_BY int(32) DEFAULT NULL,
	 MODIFIED_AT datetime DEFAULT NULL,
	 MODIFIED_BY int(32) DEFAULT NULL,
	 PRESENT_STATUS  int(1) NOT NULL,
	 ORGANIZATION_ID int(32) NOT NULL,
	 BRANCH_ID int(32) DEFAULT NULL,
	 CLAIM_ID bigint(50) NOT NULL,
	 SETTLEMENT_ID  int(11) DEFAULT NULL,
	 VENDOR_NAME varchar(256) DEFAULT NULL,
	 VENDOR_GSTIN varchar(15) DEFAULT NULL,
	 VENDOR_STATE varchar(256) DEFAULT NULL,
	 IS_REGISTERED int(1) NOT NULL,
	 INV_BILL_REF_NUMBER varchar(256) DEFAULT NULL,
	 INV_BILL_REF_DATE datetime DEFAULT NULL,
	 ITEM_SERVICE_NAME varchar(256) DEFAULT NULL,
	 HSN_SAC_CODE varchar(256) DEFAULT NULL,
	 PRODUCT_SERVICE_DESC varchar(1000) DEFAULT NULL,
	 UQC varchar(256) DEFAULT NULL,
	 QUANTITY double DEFAULT NULL,
	 RATE double DEFAULT NULL,
	 GROSS_AMOUNT double DEFAULT NULL,
	 SGST_TAX_ID int(32) DEFAULT NULL,
	 SGST_RATE double DEFAULT NULL,
	 SGST_AMOUNT double DEFAULT NULL,
	 CGST_TAX_ID int(32) DEFAULT NULL,
	 CGST_RATE double DEFAULT NULL,
	 CGST_AMOUNT double DEFAULT NULL,
	 IGST_TAX_ID int(32) DEFAULT NULL,
	 IGST_RATE double DEFAULT NULL,
	 IGST_AMOUNT double DEFAULT NULL,
	 CESS_TAX_ID int(32) DEFAULT NULL,
	 CESS_RATE double DEFAULT NULL,
	 CESS_AMOUNT double DEFAULT NULL,
	 ITEM_CATEGORY varchar(256) DEFAULT NULL,
	 PRIMARY KEY (ID),
	 KEY fk_CLAIM_DETAILS_ORGANIZATIONID (ORGANIZATION_ID),
	 KEY fk_CLAIM_DETAILS_BRANCHID (BRANCH_ID),
	 KEY fk_CLAIM_DETAILS_CLAIMID (CLAIM_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
ALTER TABLE CLAIM_DETAILS ADD CONSTRAINT fk_CLAIM_DETAILS_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CLAIM_DETAILS ADD CONSTRAINT fk_CLAIM_DETAILS_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CLAIM_DETAILS ADD CONSTRAINT fk_CLAIM_DETAILS_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CLAIM_DETAILS ADD CONSTRAINT fk_CLAIM_DETAILS_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CLAIM_DETAILS ADD CONSTRAINT fk_CLAIM_DETAILS_CALIMS_TRANSACTION FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS_TRANSACTION (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  temp_buy_on_cash_trans DROP COLUMN withORWithoutGST;
ALTER TABLE  temp_buy_on_credit_trans DROP COLUMN withORWithoutGST;

ALTER TABLE TRANSACTION_INVOICE ADD PORT_CODE varchar(256) DEFAULT NULL;

ALTER TABLE CLAIMS_SETTLEMENT ADD ITEM_GROSS_AMOUNT double DEFAULT NULL;
ALTER TABLE CLAIMS_SETTLEMENT ADD ITEM_TAX double DEFAULT NULL;
ALTER TABLE CLAIMS_TRANSACTION ADD CLAIMS_NET_TAX double DEFAULT NULL;
ALTER TABLE TRADING_INVENTORY drop foreign key FK_TRADING_INVENTORY_TRANSACTION_ID;
ALTER TABLE TRADING_INVENTORY drop key FK_TRADING_INVENTORY_TRANSACTION_ID;

DROP TABLE pay_vend_seq;
CREATE TABLE pay_vend_seq(
    counter BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (counter)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `temp_pay_vend_trans` (
  `TRAN_SER_NO` varchar(50) DEFAULT NULL,
  `TRANS_DATE` varchar(50) DEFAULT NULL,
  `BRANCH_NAME` varchar(100) DEFAULT NULL,
  `VEND_ID` varchar(100) DEFAULT NULL,
  `INV_ID` varchar(200) DEFAULT NULL,
  `PAYMENT_REC` varchar(100) DEFAULT NULL,
  `RECEIPT_TYPE` varchar(50) DEFAULT NULL,
  `BANK_DETAILS` varchar(100) DEFAULT NULL,
  `INSTRUMENT_NO` varchar(50) DEFAULT NULL,
  `INSTRUMENT_DATE` varchar(50) DEFAULT NULL,
  `RECEIPT_DETAILS` varchar(50) DEFAULT NULL,
  `TRAN_NOTE` varchar(250) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table TRANSACTION MODIFY COLUMN INSTRUMENT_NUMBER varchar(50) DEFAULT NULL;

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (35,null,null,null,null,1,'Refund Advance Received','What',1);

alter table ORGANIZATION add REFUND_ADVANCE_RECEIPT_SERIAL int(32) default 0;
alter table ORGANIZATION add REFUND_ADVANCE_RECEIPT_INTERVAL int(1) default 1;



insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (36,null,null,null,null,1,'Refund Amount Received Against Invoice','What',1);

ALTER TABLE TRANSACTION_ITEMS add COLUMN TRANSACTION_REF_NUMBER  varchar(50) DEFAULT NULL;

alter table ORGANIZATION add REFUND_AMOUNT_RECEIPT_SERIAL int(32) default 0;
alter table ORGANIZATION add REFUND_AMOUNT_RECEIPT_INTERVAL int(1) default 1;

alter table GST_FILING add CLAIM_TRANSACTION_ID int(32) default 0;
alter table GST_FILING modify column TRANSACTION_ID int(32) default 0;


update TRANSACTION_PURPOSE set PRESENT_STATUS = 0 where ID = 28;
update USER_TRANSACTION_PURPOSE set PRESENT_STATUS = 0 where TRANSACTION_PURPOSE_ID = 28;
----------------End ---180601-----------------
CREATE TABLE INTER_BRANCH_MAPPING (
  ID bigint(50) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS  int(1) NOT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  FROM_BRANCH_ID int(32) DEFAULT NULL,
  TO_BRANCH_ID int(32) DEFAULT NULL,
  OPENING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_INTER_BRANCH_MAPPING_ORGANIZATIONID (ORGANIZATION_ID),
  KEY fk_INTER_BRANCH_MAPPING_TOBRANCHID (TO_BRANCH_ID),
  KEY fk_INTER_BRANCH_MAPPING_FROMBRANCHID (FROM_BRANCH_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
ALTER TABLE INTER_BRANCH_MAPPING ADD CONSTRAINT fk_INTER_BRANCH_MAPPING_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE INTER_BRANCH_MAPPING ADD CONSTRAINT fk_INTER_BRANCH_MAPPING_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE INTER_BRANCH_MAPPING ADD CONSTRAINT fk_INTER_BRANCH_MAPPING_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE INTER_BRANCH_MAPPING ADD CONSTRAINT fk_INTER_BRANCH_MAPPING_TOBRANCH FOREIGN KEY (TO_BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE INTER_BRANCH_MAPPING ADD CONSTRAINT fk_INTER_BRANCH_MAPPING_FROMBRANCH FOREIGN KEY (FROM_BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

alter table TRIALBALANCE_INTER_BRANCH add column INTER_BRANCH_MAPPING_ID int(32) default 0;

------------External User db changes ----------------

CREATE TABLE `EXTERNAL_USER_COMPANY_DETAILS` (
   `ID` int(32) NOT NULL AUTO_INCREMENT,
   `EXTERNAL_USER_ID` INT(32) DEFAULT NULL, 
   `ACCESS_CODE` varchar(10),
   `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) DEFAULT NULL,
   `COMPANY_ORG_ID` int(32) DEFAULT NULL,
   `COMPANY_URL` TEXT,
   `CORRESPONDING_USERID` INT(32) DEFAULT NULL
,   `DATE_OF_ACCESS` DATETIME default NULL,
   `DATE_OF_ACCEPTANCE` datetime default NULL,
   `EXTERNAL_USER_STATUS` INT(2),
   PRIMARY KEY (`ID`),   
CONSTRAINT `fk_USERS` FOREIGN KEY (`EXTERNAL_USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `fk_ORGID` FOREIGN KEY (`COMPANY_ORG_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT  `fk_CORR_USER_ID` FOREIGN KEY(`CORRESPONDING_USERID`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION)ENGINE=InnoDB AUTO_INCREMENT=1 CHARSET=utf8;


INSERT INTO ROLE(NAME,PRESENT_STATUS) VALUES('EXTERNAL USER',1);
INSERT INTO ORGANIZATION (NAME,PRESENT_STATUS) VALUES ("EXTERNAL_USER_ORG",1);
INSERT INTO BRANCH(ORGANIZATION_ID,PRESENT_STATUS, NAME) VALUES((select id from ORGANIZATION where NAME = 'EXTERNAL_USER_ORG'),1,"EXTERNAL_USER_BRANCH");
alter table EXTERNAL_USER_COMPANY_DETAILS add column ORG_OTP varchar(10) DEFAULT NULL;
-------------------------------end External User db changes ------------------------------

ALTER TABLE TRANSACTION ADD column IS_BACKDATED_TRANSACTION int(1) DEFAULT 0;
ALTER TABLE PROVISION_JOURNAL_ENTRY ADD column IS_BACKDATED_TRANSACTION int(1) DEFAULT 0;
ALTER TABLE TRADING_INVENTORY ADD column IS_BACKDATED_TRANSACTION int(1) DEFAULT 0;

CREATE TABLE `withholding_type_details` (
   `ID` int(32) NOT NULL AUTO_INCREMENT,
   `NAME` text NOT NULL,
   `CREATED_AT` datetime DEFAULT NULL,
   `CREATED_BY` int(32) DEFAULT NULL,
   `MODIFIED_AT` datetime DEFAULT NULL,
   `MODIFIED_BY` int(32) DEFAULT NULL,
   `PRESENT_STATUS` int(1) NOT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=UTF8;
 

ALTER TABLE USERS ADD COLUMN THEME int(1) default null;
ALTER TABLE TRANSACTION add COLUMN INVOICE_VALUE double DEFAULT '0';


-- This is required for GSTR1 download reports for karvy, to update old data to popualte TRANSACTION.invoice_value
update TRANSACTION as T inner join (select transaction_id,sum(GROSS_AMOUNT)+sum(TOTAL_TAX) as totalVal from TRANSACTION_ITEMS where transaction_id in (select id from TRANSACTION where TRANSACTION_PURPOSE=1 and created_at > '2018-01-01' order by CREATED_AT desc) group by transaction_id) as A on A.transaction_id=T.id set T.invoice_value=A.totalVal;

update TRANSACTION as T inner join (select transaction_id,sum(GROSS_AMOUNT)+sum(TOTAL_TAX) as totalVal from TRANSACTION_ITEMS where transaction_id in (select id from TRANSACTION where TRANSACTION_PURPOSE=2 and created_at > '2018-01-01' order by CREATED_AT desc) group by transaction_id) as A on A.transaction_id=T.id set T.invoice_value=A.totalVal;

alter table SPECIFICS add column BARCODE varchar(50);

-- ORG setup for Single / MultiUser by default Multiuser
alter table ORGANIZATION add column USER_MODE int(1) default 0;

alter table CUSTOMER_DETAIL add column SAME_AS_BILLING_ADDRESS int(1) default 0;

--------180801---------------------End pwc 25.9.2018----------

CREATE TABLE USER_HAS_RIGHTS_FOR_CUSTOMER (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  CUSTOMER_ID bigint(50) DEFAULT NULL,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  TYPE int(2) DEFAULT NULL,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CUSTOMER_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_CUSTOMER_MODIFIEDBY (MODIFIED_BY),
  KEY fk_VENDOR_DETAIL_ORG (ORGANIZATION_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CUSTOMERID (CUSTOMER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CUSTOMER_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CUSTOMER_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT  fk_USER_HAS_RIGHTS_FOR_CUSTOMERID FOREIGN KEY (CUSTOMER_ID) REFERENCES VENDOR (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CUSTOMER_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CUSTOMER_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CUSTOMER_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CUSTOMER_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CUSTOMER_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE USER_HAS_RIGHTS_FOR_TAX (
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  TAX_ID int(32) DEFAULT NULL,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  TAX_TYPE int(2) NOT NULL DEFAULT 0,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_TAX_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_TAX_MODIFIEDBY (MODIFIED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_TAXID (TAX_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_TAX_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_TAX_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAXID FOREIGN KEY (TAX_ID) REFERENCES BRANCH_TAXES (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAX_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAX_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAX_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAX_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_TAX_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE USER_HAS_RIGHTS_FOR_BANK(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  BANK_ID bigint(50) DEFAULT NULL,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_BANK_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_BANK_MODIFIEDBY (MODIFIED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_BANKID (BANK_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_BANK_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_BANK_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANKID FOREIGN KEY (BANK_ID) REFERENCES BRANCH_BANK_ACCOUNTS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANK_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANK_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANK_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANK_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_BANK_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE USER_HAS_RIGHTS_FOR_CASH(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  CASH_ID bigint(50) DEFAULT NULL,
  CASH_TYPE int(1) DEFAULT 1,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CASH_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_CASH_MODIFIEDBY (MODIFIED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_CASHID (CASH_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CASH_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_CASH_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT  fk_USER_HAS_RIGHTS_FOR_CASHID FOREIGN KEY (CASH_ID) REFERENCES BRANCH_DEPOSITBOX_KEY (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CASH_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CASH_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CASH_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CASH_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_CASH_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE USER_HAS_RIGHTS_FOR_USER(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  ON_USER_ID int(32) DEFAULT NULL,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_USER_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_USER_MODIFIEDBY (MODIFIED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_ONUSERID (ON_USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_USER_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_USER_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_ONUSERID FOREIGN KEY (ON_USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_USER_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_USER_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_USER_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_USER_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_USER_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE USER_HAS_RIGHTS_FOR_INTER_BRANCH(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  USER_RIGHT_ID int(32) DEFAULT NULL,
  INTER_BRANCH_ID bigint(50) DEFAULT NULL,
  FROM_AMOUNT double DEFAULT NULL,
  TO_AMOUNT double DEFAULT NULL,
  PARTICULAR int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_CREATEDBY (CREATED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_MODIFIEDBY (MODIFIED_BY),
  KEY fk_USER_HAS_RIGHTS_FOR_INTER_BRANCHID (INTER_BRANCH_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_USERID (USER_ID),
  KEY fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_USERRIGHTID (USER_RIGHT_ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCHID FOREIGN KEY (INTER_BRANCH_ID) REFERENCES INTER_BRANCH_MAPPING (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT fk_USER_HAS_RIGHTS_FOR_INTER_BRANCH_USERRIGHTID FOREIGN KEY (USER_RIGHT_ID) REFERENCES USER_RIGHTS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

alter table PAYROLL_USER_PAYSLIP add column BRANCH_ID int(32);
alter table PAYROLL_USER_PAYSLIP add column PAY_DAYS int(2);
alter table PAYROLL_USER_PAYSLIP add column ELIGIBLE_DAYS int(2);
alter table PAYROLL_SETUP add column in_force int(1) default 1;
alter table LOG_STORED_PROC modify column MESSAGE varchar(10000);

-- Changes for Date Time
ALTER TABLE PROVISION_JOURNAL_ENTRY MODIFY TRANSACTION_DATE datetime;

ALTER TABLE VENDOR MODIFY VENDOR_SPECIFICS MEDIUMTEXT;
ALTER TABLE VENDOR MODIFY VENDOR_SPECIFICS_UNIT_PRICE MEDIUMTEXT;
ALTER TABLE VENDOR MODIFY CUSTOMER_SPECIFICS MEDIUMTEXT;
ALTER TABLE VENDOR MODIFY CUSTOMER_SPECIFICS_DISCOUNT_PERCENTAGE MEDIUMTEXT;

-----------------------------------Start TDS setup Database Changes--------------------------------------------------

ALTER TABLE VENDOR add COLUMN PAN_NO varchar(15) DEFAULT NULL;
ALTER TABLE VENDOR add COLUMN NATURE_OF_VEND int(1) DEFAULT NULL;
ALTER TABLE ORGANIZATION ADD TDS_APPLICABLE_TRANSACTIONS text;

CREATE TABLE VENDOR_TDS_BASIC (
  ID bigint(50) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS  int(1) NOT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  SPECIFICS_ID int(32) NOT NULL,
  VENDORS text DEFAULT NULL,
  FROM_DATE datetime NOT NULL,
  TO_DATE datetime NOT NULL,
  WH_TDS_SECTION_ID int(32) NOT NULL,
  MODE_OF_COMPUTE int DEFAULT NULL,
  TAX_RATE double DEFAULT NULL,
  TRANS_LIMIT double DEFAULT NULL,
  IS_OVERALL_LIMIT_APPLY int DEFAULT NULL,
  OVERALL_LIMIT double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_VENDOR_TDS_BASIC_ORGANIZATIONID (ORGANIZATION_ID),
  KEY fk_VENDOR_TDS_BASIC_SPECIFICID (SPECIFICS_ID),
  KEY fk_VENDOR_TDS_BASIC_WHTDSSECTIONID (WH_TDS_SECTION_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
ALTER TABLE VENDOR_TDS_BASIC ADD CONSTRAINT fk_VENDOR_TDS_BASIC_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_TDS_BASIC ADD CONSTRAINT fk_VENDOR_TDS_BASIC_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_TDS_BASIC ADD CONSTRAINT fk_VENDOR_TDS_BASIC_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


CREATE TABLE VENDOR_TDS_ADVANCE (
  ID bigint(50) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS  int(1) NOT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  SPECIFICS_ID int(32) NOT NULL,
  VENDOR_ID int(32) NOT NULL,
  EXPENCE_AMT double DEFAULT NULL,
  EXP_TDS_EFFECTED double DEFAULT NULL,
  ADV_PAID_NOT_ADJUSTED double DEFAULT NULL,
  ADV_TDS_EFFECTED double DEFAULT NULL,
  UPTO_DATE datetime DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_VENDOR_TDS_ADVANCE_ORGANIZATIONID (ORGANIZATION_ID),
  KEY fk_VENDOR_TDS_ADVANCE_SPECIFICID (SPECIFICS_ID),
  KEY fk_VENDOR_TDS_ADVANCE_VENDORID (VENDOR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
ALTER TABLE VENDOR_TDS_ADVANCE ADD CONSTRAINT fk_VENDOR_TDS_ADVANCE_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_TDS_ADVANCE ADD CONSTRAINT fk_VENDOR_TDS_ADVANCE_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_TDS_ADVANCE ADD CONSTRAINT fk_VENDOR_TDS_ADVANCE_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


CREATE TABLE IDOS_ADMIN_USER(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  USER_ID int(32) DEFAULT NULL,
  ACCOUNT_TYPE int DEFAULT 0,
  ACTIVE_FOR_DAYS int DEFAULT -1,
  PRIMARY KEY (ID),
  KEY fk_IDOS_ADMIN_USER_CREATEDBY (CREATED_BY),
  KEY fk_IDOS_ADMIN_USER_MODIFIEDBY (MODIFIED_BY),
  KEY fk_IDOS_ADMIN_USER_USERID (USER_ID),
  CONSTRAINT fk_IDOS_ADMIN_USER_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_IDOS_ADMIN_USER_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID),
  CONSTRAINT fk_IDOS_ADMIN_USER_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_IDOS_ADMIN_USER_USERID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

alter table PAYROLL_USERS_DATA add column PAYROLL_TYPE int(1);
alter table SPECIFICS add column GST_DESC varchar(200) default null;


alter table ORGANIZATION add column DELIVERY_CHALLAN_SERIAL_NUMBER int(32) default 0;
alter table ORGANIZATION add column DELIVER_CHALLAN_INTERVAL int(1) default null;

-- Billwise Opening Balance For Vendor And Customer

CREATE TABLE VENDOR_BILLWISE_OPENING_BAL(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  VENDOR_ID int(32) NOT NULL,
  BRANCH_ID int(32) NOT NULL,
  BILL_NO varchar(100) DEFAULT NULL,
  BILL_DATE date DEFAULT NULL,
  BILL_AMOUNT double DEFAULT NULL,
  OPENING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_VENDOR_BILLWISE_OPENING_BAL_ORGID (ORGANIZATION_ID),
  KEY fk_VENDOR_BILLWISE_OPENING_BAL_VENDORID (VENDOR_ID),
  KEY fk_VENDOR_BILLWISE_OPENING_BAL_BRANCHID (BRANCH_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE VENDOR_BILLWISE_OPENING_BAL ADD CONSTRAINT fk_VENDOR_BILLWISE_OPENING_BAL_ORGID FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_BILLWISE_OPENING_BAL ADD CONSTRAINT fk_VENDOR_BILLWISE_OPENING_BAL_BRANCHID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE CUSTOMER_BILLWISE_OPENING_BAL(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  CUSTOMER_ID int(32) NOT NULL,
  BRANCH_ID int(32) NOT NULL,
  BILL_NO varchar(100) DEFAULT NULL,
  BILL_DATE date DEFAULT NULL,
  BILL_AMOUNT double DEFAULT NULL,
  OPENING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_CUSTOMER_BILLWISE_OPENING_BAL_ORGID (ORGANIZATION_ID),
  KEY fk_CUSTOMER_BILLWISE_OPENING_BAL_CUSTOMERID (CUSTOMER_ID),
  KEY fk_CUSTOMER_BILLWISE_OPENING_BAL_BRANCHID (BRANCH_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE CUSTOMER_BILLWISE_OPENING_BAL ADD CONSTRAINT fk_CUSTOMER_BILLWISE_OPENING_BAL_ORGID FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CUSTOMER_BILLWISE_OPENING_BAL ADD CONSTRAINT fk_CUSTOMER_BILLWISE_OPENING_BAL_BRANCHID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- BranchWise Advance Balance For Vendor And Customer
CREATE TABLE CUSTOMER_BRANCHWISE_ADVANCE_BAL(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  CUSTOMER_ID int(32) NOT NULL,
  BRANCH_ID int(32) NOT NULL,
  TYPE_OF_SUPPLY int DEFAULT 0,
  CUSTOMER_DETAIL_ID int(32) NOT NULL,
  SPECIFICS_ID bigint(50) DEFAULT NULL,
  RECEIPT_NUMBER varchar(100) DEFAULT NULL,
  RECEIPT_DATE date DEFAULT NULL,
  ADVANCE_AMOUNT double DEFAULT NULL,
  OPENING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_CUSTOMER_BRANCHWISE_ADVANCE_BAL_ORGID (ORGANIZATION_ID),
  KEY fk_CUSTOMER_BRANCHWISE_ADVANCE_BAL_CUSTOMERID (CUSTOMER_ID),
  KEY fk_CUSTOMER_BRANCHWISE_ADVANCE_BAL_BRANCHID (BRANCH_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE CUSTOMER_BRANCHWISE_ADVANCE_BAL ADD CONSTRAINT fk_CUSTOMER_BRANCHWISE_ADVANCE_BAL_ORGID FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE CUSTOMER_BRANCHWISE_ADVANCE_BAL ADD CONSTRAINT fk_CUSTOMER_BRANCHWISE_ADVANCE_BAL_BRANCHID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE VENDOR_BRANCHWISE_ADVANCE_BAL(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  VENDOR_ID int(32) NOT NULL,
  BRANCH_ID int(32) NOT NULL,
  TYPE_OF_SUPPLY int DEFAULT 0,
  VENDOR_DETAIL_ID int(32) NOT NULL,
  SPECIFICS_ID bigint(50) DEFAULT NULL,
  RECEIPT_NUMBER varchar(100) DEFAULT NULL,
  RECEIPT_DATE date DEFAULT NULL,
  ADVANCE_AMOUNT double DEFAULT NULL,
  OPENING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_VENDOR_BRANCHWISE_ADVANCE_BAL_ORGID (ORGANIZATION_ID),
  KEY fk_VENDOR_BRANCHWISE_ADVANCE_BAL_VENDORID (VENDOR_ID),
  KEY fk_VENDOR_BRANCHWISE_ADVANCE_BAL_BRANCHID (BRANCH_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE VENDOR_BRANCHWISE_ADVANCE_BAL ADD CONSTRAINT fk_VENDOR_BRANCHWISE_ADVANCE_BAL_ORGID FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE VENDOR_BRANCHWISE_ADVANCE_BAL ADD CONSTRAINT fk_VENDOR_BRANCHWISE_ADVANCE_BAL_BRANCHID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE TRANSACTION_INVOICE ADD COLUMN REMARKS_ADD_DETAILS VARCHAR(512) DEFAULT NULL;

ALTER TABLE VENDOR_TDS_BASIC ADD TDS_UPLOAD_DOC text DEFAULT NULL;

-- Claim Setup New Fields
ALTER TABLE SPECIFICS add COLUMN IS_ELIGIBLE_INPUT_TAX_CREDIT int DEFAULT NULL;

ALTER TABLE USERS add COLUMN OPENING_BALANCE_ADV double DEFAULT 0;
ALTER TABLE USERS add COLUMN OPENING_BALANCE_CLAIM double DEFAULT 0;

ALTER TABLE CLAIM_DETAILS ADD COLUMN CLAIM_SPECIFICS int(32) DEFAULT NULL;
ALTER TABLE CLAIM_DETAILS ADD NET_AMOUNT double DEFAULT NULL;


CREATE TABLE `TRIALBALANCE_USER_CLAIM` (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `BRANCH_ID` int(32) DEFAULT NULL,
  `ORGNIZATION_ID` int(32) DEFAULT NULL,
  `TRANSACTION_ID` bigint(50) DEFAULT NULL,
  `TRANSACTION_PURPOSE` int(32) DEFAULT NULL,
  `TRANSACTION_SPECIFICS` bigint(50) DEFAULT NULL,
  `TRANSACTION_SPECIFICS_PARTICULARS` bigint(50) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `USER_ID` bigint(50) NOT NULL DEFAULT '0',
  `CREDIT_AMOUNT` double DEFAULT NULL,
  `DEBIT_AMOUNT` double DEFAULT NULL,
  `CLOSING_BALANCE` double DEFAULT NULL,
  PRIMARY KEY (`ID`,`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

--payroll DB Changes 

ALTER TABLE PAYROLL_SETUP ADD COLUMN IS_FIXED INT(1) DEFAULT 0;
ALTER TABLE PAYROLL_USER_PAYSLIP ADD COLUMN TRANSACTION_ACTIONDATE DATE DEFAULT NULL;
ALTER TABLE PAYROLL_USER_PAYSLIP ADD COLUMN `TRANSACTION_REF_NUMBER` varchar(50) DEFAULT NULL;

CREATE TABLE `PAYROLL_TRANSACTION` (
   `ID` int(32) NOT NULL AUTO_INCREMENT,
   `CREATED_AT` datetime DEFAULT NULL,
   `CREATED_BY` int(32) DEFAULT NULL,
   `MODIFIED_AT` datetime DEFAULT NULL,
   `MODIFIED_BY` int(32) DEFAULT NULL,
   `PAYSLIP_YEAR` int(7) NOT NULL,
   `PAYSLIP_MONTH` mediumtext NOT NULL,
   `TOTAL_INCOME1` double DEFAULT NULL,
   `TOTAL_INCOME2` double DEFAULT NULL,
   `TOTAL_INCOME3` double DEFAULT NULL,
   `TOTAL_INCOME4` double DEFAULT NULL,
   `TOTAL_INCOME5` double DEFAULT NULL,
   `TOTAL_INCOME6` double DEFAULT NULL,
   `TOTAL_INCOME7` double DEFAULT NULL,
   `TOTAL_DEDUCTION1` double DEFAULT NULL,
   `TOTAL_DEDUCTION2` double DEFAULT NULL,
   `TOTAL_DEDUCTION3` double DEFAULT NULL,
   `TOTAL_DEDUCTION4` double DEFAULT NULL,
   `TOTAL_DEDUCTION5` double DEFAULT NULL,
   `TOTAL_DEDUCTION6` double DEFAULT NULL,
   `TOTAL_DEDUCTION7` double DEFAULT NULL,
   `TOTAL_TOTAL_INCOME` double DEFAULT NULL,
   `TOTAL_TOTAL_DEDUCTION` double DEFAULT NULL,
   `TOTAL_NET_PAY` double DEFAULT NULL,
   `SUPPORTING_DOCS` text,
   `TRANSACTION_ACTIONDATE` date DEFAULT NULL,
   `TRANSACTION_REF_NUMBER` varchar(50) DEFAULT NULL,
   `APPROVER_EMAILS` text,
   `ADDITIONAL_APPROVER_USER_EMAILS` text,
   `SELECTED_ADDITIONAL_APPROVER` text,
   `TRANSACTION_PURPOSE` int(11) DEFAULT NULL,
   `TRANSACTION_STATUS` text,
   `APPROVER_ACTION_BY` int(31) DEFAULT NULL,
   `ORGANIZATION_ID` int(32) NOT NULL,
   `BRANCH_ID` int(32) DEFAULT NULL,
   `ELIGIBLE_DAYS` int(2) DEFAULT NULL,
   `PAY_DAYS` int(2) DEFAULT NULL,
   `PRESENT_STATUS` int(1) DEFAULT NULL,
   `TRANSACTION_BRANCH_BANK` bigint(50) DEFAULT NULL,
   `INSTRUMENT_NUMBER` varchar(50) DEFAULT NULL,
   `INSTRUMENT_DATE` varchar(50) DEFAULT NULL,
   `REMARKS` text,
   `PAY_MODE` text,
   PRIMARY KEY (`ID`),
   KEY `fk_PAYROLL_TXN_TRANSACTION_PURPOSE` (`TRANSACTION_PURPOSE`),
   CONSTRAINT `fk_PAYROLL_TXN_TRANSACTION_PURPOSE` FOREIGN KEY (`TRANSACTION_PURPOSE`) REFERENCES `TRANSACTION_PURPOSE` (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8;

ALTER TABLE TRADING_INVENTORY ADD INVENTORY_TYPE int(1) DEFAULT NULL;
ALTER TABLE TRADING_INVENTORY ADD PRICE_CHANGED_TXN varchar(512) DEFAULT null;

UPDATE SPECIFICS set IS_ELIGIBLE_INPUT_TAX_CREDIT = 0 where IS_ELIGIBLE_INPUT_TAX_CREDIT IS NULL;
ALTER TABLE SPECIFICS add COLUMN IS_COMPOSITION_SCHEME int DEFAULT 0;
ALTER TABLE SPECIFICS add COLUMN CESS_TAX_RATE double DEFAULT NULL;


ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME1_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME1_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME2_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME2_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME3_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME3_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME4_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME4_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME5_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME5_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME6_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME6_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column INCOME7_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column INCOME7_ID int(32);

ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU1_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU1_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU2_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU2_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU3_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU3_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU4_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU4_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU5_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU5_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU6_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU6_ID int(32);
ALTER TABLE PAYROLL_USER_PAYSLIP add column DEDU7_ID int(32);
ALTER TABLE PAYROLL_TRANSACTION add column DEDU7_ID int(32);

 CREATE TABLE TRIALBALANCE_PAYROLL_ITEM (
  ID bigint(50) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) NOT NULL,
  ORGANIZATION_ID int(32) DEFAULT NULL,
  BRANCH_ID int(32) DEFAULT NULL,
  TRANSACTION_ID bigint(50) DEFAULT NULL,
  USER_ID bigint(50) NOT NULL,
  TRANSACTION_PURPOSE int(32) DEFAULT NULL,
  TRANSACTION_SPECIFICS bigint(50) DEFAULT NULL,
  TRANSACTION_SPECIFICS_PARTICULARS bigint(50) DEFAULT NULL,
  DATE date DEFAULT NULL,
  CREDIT_AMOUNT double DEFAULT NULL,
  DEBIT_AMOUNT double DEFAULT NULL,
  CLOSING_BALANCE double DEFAULT NULL,
  PRIMARY KEY (ID,USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

alter table PAYROLL_TRANSACTION change TOTAL_INCOME1 TOTAL_EARNING1 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME2 TOTAL_EARNING2 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME3 TOTAL_EARNING3 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME4 TOTAL_EARNING4 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME5 TOTAL_EARNING5 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME6 TOTAL_EARNING6 double;
alter table PAYROLL_TRANSACTION change TOTAL_INCOME7 TOTAL_EARNING7 double;

alter table PAYROLL_TRANSACTION change INCOME1_ID EARNING1_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME2_ID EARNING2_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME3_ID EARNING3_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME4_ID EARNING4_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME5_ID EARNING5_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME6_ID EARNING6_ID int(32);
alter table PAYROLL_TRANSACTION change INCOME7_ID EARNING7_ID int(32);

alter table PAYROLL_TRANSACTION change DEDU1_ID DEDUCTION1_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU2_ID DEDUCTION2_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU3_ID DEDUCTION3_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU4_ID DEDUCTION4_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU5_ID DEDUCTION5_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU6_ID DEDUCTION6_ID int(32);
alter table PAYROLL_TRANSACTION change DEDU7_ID DEDUCTION7_ID int(32);

alter table PAYROLL_USER_PAYSLIP change INCOME1 EARNING1 double;
alter table PAYROLL_USER_PAYSLIP change INCOME2 EARNING2 double;
alter table PAYROLL_USER_PAYSLIP change INCOME3 EARNING3 double;
alter table PAYROLL_USER_PAYSLIP change INCOME4 EARNING4 double;
alter table PAYROLL_USER_PAYSLIP change INCOME5 EARNING5 double;
alter table PAYROLL_USER_PAYSLIP change INCOME6 EARNING6 double;
alter table PAYROLL_USER_PAYSLIP change INCOME7 EARNING7 double;
alter table PAYROLL_USER_PAYSLIP change TOTAL_INCOME TOTAL_EARNING  double;

alter table PAYROLL_USER_PAYSLIP change INCOME1_ID EARNING1_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME2_ID EARNING2_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME3_ID EARNING3_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME4_ID EARNING4_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME5_ID EARNING5_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME6_ID EARNING6_ID int(32);
alter table PAYROLL_USER_PAYSLIP change INCOME7_ID EARNING7_ID int(32);

alter table PAYROLL_USER_PAYSLIP change DEDU1_ID DEDUCTION1_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU2_ID DEDUCTION2_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU3_ID DEDUCTION3_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU4_ID DEDUCTION4_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU5_ID DEDUCTION5_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU6_ID DEDUCTION6_ID int(32);
alter table PAYROLL_USER_PAYSLIP change DEDU7_ID DEDUCTION7_ID int(32);

ALTER TABLE PAYROLL_SETUP add column OPENING_BALANCE double default null;

CREATE TABLE PAID_CLAIM_DETAILS(
  ID int(32) NOT NULL AUTO_INCREMENT,
  CREATED_AT datetime DEFAULT NULL,
  CREATED_BY int(32) DEFAULT NULL,
  MODIFIED_AT datetime DEFAULT NULL,
  MODIFIED_BY int(32) DEFAULT NULL,
  PRESENT_STATUS int(1) DEFAULT NULL,
  ORGANIZATION_ID int(32) NOT NULL,
  CLAIM_ID int(32) NOT NULL,
  PAID_AMT double DEFAULT NULL,
  PAY_MODE varchar(50) DEFAULT NULL,
  PAYMENT_DATE date DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_PAID_CLAIM_DETAILS_ORGID (ORGANIZATION_ID),
  KEY fk_PAID_CLAIM_DETAILS_CLAIMID (CLAIM_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE PAID_CLAIM_DETAILS ADD CONSTRAINT fk_PAID_CLAIM_DETAILS_ORGID FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSACTION_INVOICE ADD COLUMN INVOICE_HEADING INT(1) DEFAULT 0;
--------------------- Changes FOr BACKDATED TRANSCTIONS -------------------------
ALTER TABLE ORGANIZATION add COLUMN LIMIT_FOR_BACKDATED_TXN int DEFAULT 0;

ALTER TABLE BRANCH_SPECIFICS_TAX_FORMULA ADD COLUMN APPLICABLE_FROM datetime DEFAULT NULL;
UPDATE BRANCH_SPECIFICS_TAX_FORMULA SET APPLICABLE_FROM=CREATED_AT;

ALTER TABLE TRANSACTION_INVOICE ADD COLUMN REASON_FOR_RETURN INT(1) DEFAULT null;

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (37,null,null,null,null,1,'Reversal of ITC','What',1);

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (38,null,null,null,null,1,'Cancellation/Voiding Invoice','How Much',1);

ALTER TABLE TRANSACTION_ITEMS add COLUMN REASON_FOR_RETURN INT(1) DEFAULT null;

ALTER TABLE ORGANIZATION add COLUMN PAYMENT_VOUCHER_SERIAL_NUMBER INT(32) DEFAULT 0;
ALTER TABLE ORGANIZATION add COLUMN PAYMENT_VOUCHER_INTERVAL INT(1) DEFAULT null;

CREATE TABLE BILL_OF_MATERIAL(
  ID bigint(50) not null AUTO_INCREMENT,
  CREATED_AT datetime not null,
  CREATED_BY int(32) not null,
  MODIFIED_AT datetime default null,
  MODIFIED_BY int(32) default null,
  PRESENT_STATUS int(1) default 1,
  ORGANIZATION_ID int(32) not null,
  BRANCH_ID int(32) not null,
  PROJECT_ID int(32) default null,
  INCOME_ID bigint(50) not null,
  PRIMARY KEY (ID),
  KEY fk_BILL_OF_MATERIAL_CREATED (CREATED_BY),
  KEY fk_BILL_OF_MATERIAL_MODIFIED (MODIFIED_BY),
  KEY fk_BILL_OF_MATERIAL_ORG (ORGANIZATION_ID),
  KEY fk_BILL_OF_MATERIAL_BRANCH (BRANCH_ID),
  KEY fk_BILL_OF_MATERIAL_PROJECT (PROJECT_ID),
  KEY fk_BILL_OF_MATERIAL_INCOME (INCOME_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_MODIFIED FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_INCOME FOREIGN KEY (INCOME_ID) REFERENCES SPECIFICS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE BILL_OF_MATERIAL_ITEM(
  ID int(32) not null AUTO_INCREMENT,
  CREATED_AT datetime default null,
  CREATED_BY int(32) default null,
  MODIFIED_AT datetime default null,
  MODIFIED_BY int(32) default null,
  PRESENT_STATUS int(1) default 1,
  BILL_OF_MATERIAL_ID bigint(50) not null,
  ORGANIZATION_ID int(32) not null,
  BRANCH_ID int(32) not null,
  VENDOR_ID bigint(50) not null,
  EXPENSE_ID bigint(50) not null,
  MEASURE_NAME varchar(256) default null,
  OEM varchar(256) default null,
  NO_OF_UNITS double default null,
  TYPE_OF_MATERIAL varchar(256) default null,
  KNOWLEDGE_LIB varchar(512) default null,
  PRIMARY KEY (ID),
  KEY fk_BILL_OF_MATERIAL_ITEM_CREATED (CREATED_BY),
  KEY fk_BILL_OF_MATERIAL_ITEM_MODIFIED (MODIFIED_BY),
  KEY fk_BILL_OF_MATERIAL_ITEM_BOM (BILL_OF_MATERIAL_ID),
  KEY fk_BILL_OF_MATERIAL_ITEM_ORG (ORGANIZATION_ID),
  KEY fk_BILL_OF_MATERIAL_ITEM_BRANCH (BRANCH_ID),
  KEY fk_BILL_OF_MATERIAL_ITEM_VENDOR (VENDOR_ID),
  KEY fk_BILL_OF_MATERIAL_ITEM_EXPENSE (EXPENSE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_MODIFIED FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_BOM FOREIGN KEY (BILL_OF_MATERIAL_ID) REFERENCES BILL_OF_MATERIAL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_ITEM_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPECIFICS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (39,null,null,null,null,1,'Create Sales Order/Bill Of Material','How Much',1);

ALTER TABLE TRANSACTION_ITEMS add COLUMN OEM varchar(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS add COLUMN UNIT_OF_MEASURE varchar(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS add COLUMN VEND_CUST_ID bigint(50) DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS add COLUMN TYPE_OF_MATERIAL int(2) DEFAULT NULL;
ALTER TABLE TRANSACTION_ITEMS add COLUMN KNOWLEDGE_LIB int(2) DEFAULT NULL;


ALTER TABLE ORGANIZATION add COLUMN SELF_INVOICE_NUMBER int(32) DEFAULT 0;
ALTER TABLE ORGANIZATION add COLUMN SELF_INVOICE_INTERVAL int(32);

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (40,null,null,null,null,1,'Create Purchase Requisition','What',1);

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (41,null,null,null,null,1,'Create Purchase Order','What',1);

insert into `TRANSACTION_PURPOSE`(`ID`,`CREATED_AT`,`CREATED_BY`,`MODIFIED_AT`,`MODIFIED_BY`,`PRESENT_STATUS`,`TRANSACTION_PURPOSE`,`NEXT_QUESTION`,`QUESTION_TYPE`) values (42,null,null,null,null,1,'Material Issue Note','What',1);

CREATE TABLE BILL_OF_MATERIAL_TXN(
  ID bigint(50) not null auto_increment,
  CREATED_AT datetime not null,
  CREATED_BY int(32) not null,
  MODIFIED_AT datetime default null,
  MODIFIED_BY int(32) default null,
  PRESENT_STATUS int(1) default 1,
  ORGANIZATION_ID int(32) not null,
  BRANCH_ID int(32) not null,
  PROJECT_ID int(32) default null,
  CUSTOMER_VENDOR_ID bigint(50) default null,
  INCOME_ID bigint(50) default null,
  BOM_SETUP_ID bigint(50) default null,
  TRANSACTION_PURPOSE int(11) not null,
  SOURCE_GSTIN varchar(20) default null,
  DESTINATION_GSTIN varchar(20) default null,
  ACTION_DATE datetime default current_timestamp,
  INCOME_NO_OF_UNITS double default null,
  TOTAL_NO_OF_UNITS double default null,
  TOTAL_AMOUNT double default null,
  TOTAL_NET_AMOUNT double default null,
  TRANSACTION_STATUS varchar(64) not null,
  TRANSACTION_REF_NUMBER varchar(128) default null,
  LINKED_REF_NO varchar(128) default null,
  DOCUMENT_REF varchar(1024) default null,
  APPROVER_EMAILS varchar(1024) default null,
  ADDITIONAL_APPROVER_USER_EMAILS varchar(1024) default null,
  SELECTED_ADDITIONAL_APPROVER varchar(1024) default null,
  APPROVER_ACTION_BY int(32) default null,
  REMARKS varchar(1024) default null,
  PRIVATE_REMARKS varchar(1024) default null,
  SUPPORTING_DOCS varchar(2048) default null,
  IS_FULFILLED int(1) default 0,
  FULFILLED_UNITS double default 0,
  INVOICE_NUMBER varchar(64) default NULL,
  TYPE_IDENTIFIER int(1) default -1,
  PRIMARY KEY (ID),
  KEY fk_BILL_OF_MATERIAL_TXN_CREATED (CREATED_BY),
  KEY fk_BILL_OF_MATERIAL_TXN_MODIFIED (MODIFIED_BY),
  KEY fk_BILL_OF_MATERIAL_TXN_ORG (ORGANIZATION_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_BRANCH (BRANCH_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_PROJECT (PROJECT_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_INCOME (INCOME_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_CUSTOMER_VENDOR (CUSTOMER_VENDOR_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_BOM_SETUP (BOM_SETUP_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_PURPOSE (TRANSACTION_PURPOSE)
) ENGINE=InnoDB AUTO_INCREMENT=1 default CHARSET=UTF8;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_MODIFIED FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_INCOME FOREIGN KEY (INCOME_ID) REFERENCES SPECIFICS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_CUSTOMER_VENDOR FOREIGN KEY (CUSTOMER_VENDOR_ID) REFERENCES VENDOR (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_BOM_SETUP FOREIGN KEY (BOM_SETUP_ID) REFERENCES BILL_OF_MATERIAL (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_PURPOSE FOREIGN KEY (TRANSACTION_PURPOSE) REFERENCES TRANSACTION_PURPOSE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE BILL_OF_MATERIAL_TXN_ITEM(
  ID int(32) not null auto_increment,
  CREATED_AT datetime default null,
  CREATED_BY int(32) default null,
  MODIFIED_AT datetime default null,
  MODIFIED_BY int(32) default null,
  PRESENT_STATUS int(1) default 1,
  BOM_TXN_ID bigint(50) not null,
  ORGANIZATION_ID int(32) not null,
  BRANCH_ID int(32) not null,
  VENDOR_ID bigint(50) default null,
  EXPENSE_ID bigint(50) not null,
  MEASURE_NAME varchar(256) default null,
  OEM varchar(256) default null,
  NO_OF_UNITS double default null,
  PRICE_PER_UNIT double default null,
  TOTAL_PRICE double default null,
  TYPE_OF_MATERIAL varchar(256) default null,
  AVAILABLE_UNITS double default null,
  COMMITTED_UNITS double default null,
  ORDERED_UNITS	 double default null,
  NET_UNITS double default null,
  EXPECTED_DATETIME datetime default current_timestamp,
  KLFOLLOW_STATUS int(1) default null,
  DESTINATION_GSTIN varchar(20) default null,
  IS_FULFILLED int(1) default 0,
  FULFILLED_UNITS double default 0,
  PRIMARY KEY (ID),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_CREATED (CREATED_BY),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_MODIFIED (MODIFIED_BY),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_BOM (BOM_TXN_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_ORG (ORGANIZATION_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_BRANCH (BRANCH_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_VENDOR (VENDOR_ID),
  KEY fk_BILL_OF_MATERIAL_TXN_ITEM_EXPENSE (EXPENSE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 default CHARSET=UTF8;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_CREATED FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_MODIFIED FOREIGN KEY (MODIFIED_BY) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_BOM FOREIGN KEY (BOM_TXN_ID) REFERENCES BILL_OF_MATERIAL_TXN (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BILL_OF_MATERIAL_TXN_ITEM ADD CONSTRAINT fk_BILL_OF_MATERIAL_TXN_ITEM_EXPENSE FOREIGN KEY (EXPENSE_ID) REFERENCES SPECIFICS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE BILL_OF_MATERIAL_TXN MODIFY COLUMN TYPE_IDENTIFIER int(2) default -1;

--Digital Signature
alter table TRANSACTION_INVOICE add column DIGITAL_SIGNATURE_CONTENT varchar(512);

CREATE TABLE DIGITAL_SIGNATURE_BRANCH_WISE(
  ID int(32) not null auto_increment,
  CREATED_AT datetime default null,
  CREATED_BY int(32) default null,
  MODIFIED_AT datetime default null,
  MODIFIED_BY int(32) default null,
  PRESENT_STATUS int(1) default 1,
  ORGANIZATION_ID int(32) not null,
  BRANCH_ID int(32) not null,
  PERSON_NAME VARCHAR(750),
  DESIGNATION VARCHAR(100),
  PHONE_NO VARCHAR(15),
  EMAIL_ID VARCHAR(256),
  DIGITAL_SIGN_DOCUMENTS VARCHAR(25),
  REF_NO VARCHAR(256),
  KYC_DETAILS VARCHAR(256),
  PRIMARY KEY (`ID`),
  KEY `fk_DIGITAL_SIGN_CREATEDBY` (`CREATED_BY`),
  KEY `fk_DIGITAL_SIGN_MODIFIEDBY` (`MODIFIED_BY`),
  KEY `fk_DIGITAL_SIGN_ORG` (`ORGANIZATION_ID`),
  KEY `fk_DIGITAL_SIGN_BRANCH` (`BRANCH_ID`),
  CONSTRAINT `fk_DIGITAL_SIGN_CREATEDBY` FOREIGN KEY (`CREATED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIGITAL_SIGN_MODIFIEDBY` FOREIGN KEY (`MODIFIED_BY`) REFERENCES `USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIGITAL_SIGN_ORG` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIGITAL_SIGN_BRANCH` FOREIGN KEY (`BRANCH_ID`) REFERENCES `BRANCH` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
alter table DIGITAL_SIGNATURE_BRANCH_WISE add column VALIDITY_FROM varchar(20);
alter table DIGITAL_SIGNATURE_BRANCH_WISE add column VALIDITY_TO varchar(20);

-- CREATE PURCHASE ORDER Invoice No--
alter table ORGANIZATION add column CREATE_PURCHASE_ORDER_SERIAL int(32) default 0;
alter table ORGANIZATION add column CREATE_PURCHASE_ORDER_INTERVAL int(1) default 0;

UPDATE TRIALBALANCE_TAXES SET tax_type = 6 where tax_type=3;

CREATE TABLE `TRIALBALANCE_DISCOUNT` (
   `ID` bigint(50) NOT NULL AUTO_INCREMENT,
   `CREATED_AT` datetime DEFAULT NULL,
   `CREATED_BY` int(32) DEFAULT NULL,
   `MODIFIED_AT` datetime DEFAULT NULL,
   `MODIFIED_BY` int(32) DEFAULT NULL,
   `PRESENT_STATUS` int(1) NOT NULL,
   `TRANSACTION_ID` bigint(50) NOT NULL,
   `TRANSACTION_PURPOSE` int(32) NOT NULL,
   `DATE` date DEFAULT NULL,
   `BRANCH_ID` int(32) NOT NULL,
   `BRANCH_ORGNIZATION_ID` int(32) NOT NULL,
   `CREDIT_AMOUNT` double DEFAULT NULL,
   `DEBIT_AMOUNT` double DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
 
 ALTER TABLE TRIALBALANCE_DISCOUNT ADD COLUMN TRANSACTION_SPECIFICS bigint(50);
 
 -- ***************** ONLY FOR PWC PORT START ******************--
 
 UPDATE TRANSACTION_PURPOSE SET PRESENT_STATUS = 0 where ID in (34,39,40,41,42);
 DELETE FROM USER_TRANSACTION_PURPOSE where TRANSACTION_PURPOSE_ID in (34,39,40,41,42);
 
 // ***************************** 
 ALTER TABLE SPECIFICS ADD COLUMN TAX_APPLICABLE_DATE datetime DEFAULT NULL;
 
  ALTER TABLE SPECIFICS ADD COLUMN GST_TAX_RATE_SELECTED varchar(50) default null;
  ALTER TABLE SPECIFICS ADD COLUMN CESS_TAX_RATE_SELECTED varchar(50) default null;
  
  
  ALTER TABLE VENDOR_has_SPECIFICS ADD COLUMN VEND_RCM_TAX_RATE double DEFAULT NULL;
  ALTER TABLE VENDOR_has_SPECIFICS ADD COLUMN VEND_CESS_TAX_RATE double DEFAULT NULL;
  ALTER TABLE VENDOR_has_SPECIFICS ADD COLUMN VEND_TAX_APPLICABLE_DATE datetime DEFAULT NULL;
  
 ALTER TABLE SPECIFICS add COLUMN IS_TDS_VENDOR_SPEC int DEFAULT 0;
 
 ALTER TABLE VENDOR_TDS_ADVANCE add COLUMN TDS_BASIC_ID bigint(50) DEFAULT NULL;
 
 DROP INDEX `fk_VENDOR_TDS_BASIC_SPECIFICID` ON `VENDOR_TDS_BASIC`

ALTER TABLE VENDOR_TDS_BASIC MODIFY SPECIFICS_ID int(32);

DROP INDEX `fk_VENDOR_TDS_ADVANCE_SPECIFICID` ON `VENDOR_TDS_ADVANCE`

ALTER TABLE VENDOR_TDS_ADVANCE MODIFY SPECIFICS_ID int(32);

ALTER TABLE VENDOR add COLUMN PLACE_OF_SUPPLY_TYPE int DEFAULT 1;
 
ALTER TABLE VENDOR ADD COLUMN VENDOR_SPECIFICS_RCM_CESS_RATE TEXT DEFAULT NULL;
ALTER TABLE VENDOR ADD COLUMN VENDOR_SPECIFICS_RCM_TAX_RATE TEXT DEFAULT NULL;
ALTER TABLE VENDOR ADD COLUMN VENDOR_SPECIFICS_RCM_APPLICABLE_DATE TEXT DEFAULT NULL;

CREATE TABLE `SPECIFIC_TAX_HISTORY` (
   `ID` bigint(50) NOT NULL AUTO_INCREMENT,
   `CREATED_AT` datetime DEFAULT NULL,
   `CREATED_BY` int(32) DEFAULT NULL,
   `MODIFIED_AT` datetime DEFAULT NULL,
   `MODIFIED_BY` int(32) DEFAULT NULL,
   `PRESENT_STATUS` int(1) NOT NULL,
   `SPECIFIC_ID` bigint(50) NOT NULL,
   `ORGNIZATION_ID` int(32) NOT NULL,
   `TAX_RATE` double DEFAULT NULL,
   `CESS_RATE` double DEFAULT NULL,
   `APPLICABLE_DATE` datetime DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
 
 
alter table BILL_OF_MATERIAL_TXN_ITEM add column `FULFILLED_TXN_REF_NO` varchar(2000) DEFAULT NULL;

alter table ORGANIZATION add column FILE_UPLOAD_DESTINATION int(1) default 0;

------------------------
CREATE TABLE IDOS_FILE_UPLOAD_LOGS (
	ID bigint(50) NOT NULL AUTO_INCREMENT,
	CREATED_AT datetime DEFAULT NULL,
	CREATED_BY int(32) DEFAULT NULL,
	MODIFIED_AT datetime DEFAULT NULL,
	MODIFIED_BY int(32) DEFAULT NULL,
	PRESENT_STATUS int(1) DEFAULT NULL,
	ORGANIZATION_ID int(32) DEFAULT NULL,
    BRANCH_ID bigint(50) DEFAULT NULL,
    REFERENCE_ID bigint(50) DEFAULT NULL,
	UPLOAD_MODULE varchar(256) DEFAULT NULL,
	UPLOAD_MODULE_ELEMENT varchar(256) DEFAULT NULL,
	DESTINATION int(1) DEFAULT 0,
	FILE_NAME varchar(500) DEFAULT NULL,
	FILE_URL varchar(500) DEFAULT NULL,
	FILE_SIZE bigint(50) NOT NULL,
	PRIMARY KEY (ID),
	index idx_IDOS_FILE_UPLOAD_LOGS_ORGANIZATION_ID (ORGANIZATION_ID),
	index idx_IDOS_FILE_UPLOAD_LOGS_REFERENCE_ID (REFERENCE_ID)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

ALTER TABLE USERS ADD COLUMN AGREED_TERMS_AND_CONDITIONS int(1) default 0;

CREATE TABLE ORGANIZATION_CONFIG (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(32) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(32) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `PARAM_NAME` varchar(256) NOT NULL,
  `PARAM_VALUE` varchar(256) NOT NULL,
  `PARAM_DESCRIPTION` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT fk_ORGANIZATION_CONFIG_ORG FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES ORGANIZATION (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
 
--please verify tablesdata.sql, one marked query has to be executed before running the below query(line no. 40), to keep the old data intact-- 
drop table TRIALBALANCE_DISCOUNT;

CREATE TABLE LEDGER_COA_MAPPING (
  `ID` bigint(50) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(1) NOT NULL,
  `ORGANIZATION_ID` int(32) NOT NULL,
  `BRANCH_ID` int(32) DEFAULT NULL,
  `LEDGER_ID` bigint(50) NOT NULL,
  `LEDGER_TYPE` varchar(50) NOT NULL,
  `MAPPING_TYPE` int(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_LEDGER_COA_MAPPING` (`ORGANIZATION_ID`,`LEDGER_ID`,`LEDGER_TYPE`, MAPPING_TYPE)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `IDOS_CONFIG_PARAM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_AT` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `PRESENT_STATUS` int(11) DEFAULT NULL,
  `PARAM_NAME` varchar(255) NOT NULL,
  `PARAM_VALUE` varchar(2048) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_IDOS_CONFIG_PARAM` (`PARAM_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE IDOS_CONFIG_PARAM MODIFY COLUMN PARAM_VALUE VARCHAR(2040);
ALTER TABLE ORGANIZATION_KEY_OFFICIALS ADD COLUMN UPLOADED_KYC_URL varchar(256) DEFAULT NULL;

-- ***************** FOR UPLOADS ******************--


CREATE TABLE IDOS_UPLOADLOG ( 
  ID bigint primary key not null,
  FILENAME  varchar (50), 
  TIMESTAMP		DATE,
  TOTALRECORDS		bigint	 (10) DEFAULT 0,
  RECORDSINSERTED	bigint   (10) DEFAULT 0,
  RECORDSDELETED	bigint   (10) DEFAULT 0,	
  RECORDSUPDATED	bigint   (10) DEFAULT 0,
  RECORDSIGNORED	bigint   (10) DEFAULT 0,
  STATUS		varchar (100),
  OPERATION       varchar(56)
  )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8; 
  
CREATE TABLE IDOS_FILES_LOG(
    ID bigint (19) not null,
    CREATED_AT  date  not null,
    CREATED_BY int (10),
    MODIFIED_AT date,
    MODIFIED_BY int (10),
    PRESENT_STATUS int (1) default 1 not null,
    FILE_NAME varchar (128),
    TIMESTAMP   DATE,
    TABLE_NAME varchar (128),
    TOTAL_RECORDS int (10) DEFAULT 0,
    RECORDS_INSERTED int (10) DEFAULT 0,
    RECORDS_DELETED int (10) DEFAULT 0,
    RECORDS_UPDATED int (10) DEFAULT 0,
    RECORDS_IGNORED int (10) DEFAULT 0,
    SEGMENT_NAME varchar (56),
    OPERATION varchar (56),
    primary key (ID) 
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
  
  
CREATE TABLE TRANSACTION_TMP(
 ORDR_DATE   VARCHAR(255) DEFAULT NULL,
 SRC_CITY  VARCHAR(255) DEFAULT NULL,
 SELLER_ID    BIGINT(20) NOT NULL,
 BUYER_ID   BIGINT(20) NOT NULL,
 DSTN_CITY  VARCHAR(255) DEFAULT NULL,
 ORDR_ID  BIGINT(20) NOT NULL,
 INV_NO    BIGINT(20) NOT NULL,
 INV_DATE  VARCHAR(255)  DEFAULT NULL,
 CTGRY  VARCHAR(55) DEFAULT NULL,
 TOTAL_INV BIGINT(20) NOT NULL,
 FILE_NAME VARCHAR(255) NOT NULL,
 USER_ID BIGINT(20) NOT NULL
);
