package com.idos.util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CountryTelephoneCodeUtil {
	private static Map<String, String> country2phone = new HashMap<String, String>();
	static {
	    country2phone.put("AF", "Afghanistan(+93)");
	    country2phone.put("AL", "Albania(+355)");
	    country2phone.put("DZ", "Algeria(+213)");
	    country2phone.put("AD", "Andorra(+376)");
	    country2phone.put("AO", "Angola(+244)");
	    country2phone.put("AG", "Antigua(+1-268)");
	    country2phone.put("AR", "Argentina(+54)");
	    country2phone.put("AM", "Armenia(+374)");
	    country2phone.put("AU", "Australia(+61)");
	    country2phone.put("AT", "Austria(+43)");
	    country2phone.put("AZ", "Azerbaijan(+994)");
	    country2phone.put("BS", "Bahamas(+1-242)");
	    country2phone.put("BH", "Bahrain(+973)");
	    country2phone.put("BD", "Bangladesh(+880)");
	    country2phone.put("BB", "Barbados(+1-246)");
	    country2phone.put("BY", "Belarus(+375)");
	    country2phone.put("BE", "Belgium(+32)");
	    country2phone.put("BZ", "Belize(+501)");
	    country2phone.put("BJ", "Benin(+229)");
	    country2phone.put("BT", "Bhutan(+975)");
	    country2phone.put("BO", "Bolivia(+591)");
	    country2phone.put("BA", "Bosnia(+387)");
	    country2phone.put("BW", "Botswana(+267)");
	    country2phone.put("BR", "Brazil(+55)");
	    country2phone.put("BN", "Brunei(+673)");
	    country2phone.put("BG", "Bulgaria(+359)");
	    country2phone.put("BF", "Burkina Faso(+226)");
	    country2phone.put("BI", "Burundi(+257)");
	    country2phone.put("KH", "Cambodia(+855)");
	    country2phone.put("CM", "Cameroon(+237)");
	    country2phone.put("CA", "Canada(+1)");
	    country2phone.put("CV", "Cape Verde(+238)");
	    country2phone.put("CF", "AfricanRepublic(+236)");
	    country2phone.put("TD", "Chad(+235)");
	    country2phone.put("CL", "Chile(+56)");
	    country2phone.put("CN", "China(+86)");
	    country2phone.put("CO", "Colombia(+57)");
	    country2phone.put("KM", "Comoros(+269)");
	    country2phone.put("CD", "Congo–Kinshasa(+243)");
	    country2phone.put("CG", "Congo–Brazzaville(+242)");
	    country2phone.put("CR", "Costa Rica(+506)");
	    country2phone.put("CI", "Coted'Ivoire(+225)");
	    country2phone.put("HR", "Croatia(+385)");
	    country2phone.put("CU", "Cuba(+53)");
	    country2phone.put("CY", "Cyprus(+357)");
	    country2phone.put("CZ", "Czech Republic(+420)");
	    country2phone.put("DK", "Denmark(+45)");
	    country2phone.put("DJ", "Djibouti(+253)");
	    country2phone.put("DM", "Dominica(+1-767)");
	    country2phone.put("DO", "DominicanRepublic(+1-809)");
	    country2phone.put("EC", "Ecuador(+593)");
	    country2phone.put("EG", "Egypt(+20)");
	    country2phone.put("SV", "ElSalvador(+503)");
	    country2phone.put("GQ", "EquatorialGuinea(+240)");
	    country2phone.put("ER", "Eritrea(+291)");
	    country2phone.put("EE", "Estonia(+372)");
	    country2phone.put("ET", "Ethiopia(+251)");
	    country2phone.put("FJ", "Fiji(+679)");
	    country2phone.put("FI", "Finland(+358)");
	    country2phone.put("FR", "France(+33)");
	    country2phone.put("GA", "Gabon(+241)");
	    country2phone.put("GM", "Gambia(+220)");
	    country2phone.put("GE", "Georgia(+995)");
	    country2phone.put("DE", "Germany(+49)");
	    country2phone.put("GH", "Ghana(+233)");
	    country2phone.put("GR", "Greece(+30)");
	    country2phone.put("GD", "Grenada(+1-473)");
	    country2phone.put("GT", "Guatemala(+502)");
	    country2phone.put("GN", "Guinea(+224)");
	    country2phone.put("GW", "Guinea-Bissau(+245)");
	    country2phone.put("GY", "Guyana(+592)");
	    country2phone.put("HT", "Haiti(+509)");
	    country2phone.put("HN", "Honduras(+504)");
	    country2phone.put("HU", "Hungary(+36)");
	    country2phone.put("IS", "Iceland(+354)");
	    country2phone.put("IN", "India(+91)");
	    country2phone.put("ID", "Indonesia(+62)");
	    country2phone.put("IR", "Iran(+98)");
	    country2phone.put("IQ", "Iraq(+964)");
	    country2phone.put("IE", "Ireland(+353)");
	    country2phone.put("IL", "Israel(+972)");
	    country2phone.put("IT", "Italy(+39)");
	    country2phone.put("JM", "Jamaica(+1-876)");
	    country2phone.put("JP", "Japan(+81)");
	    country2phone.put("JO", "Jordan(+962)");
	    country2phone.put("KZ", "Kazakhstan(+7)");
	    country2phone.put("KE", "Kenya(+254)");
	    country2phone.put("KI", "Kiribati(+686)");
	    country2phone.put("KP", "North Korea(+850)");
	    country2phone.put("KR", "South Korea(+82)");
	    country2phone.put("KW", "Kuwait(+965)");
	    country2phone.put("KG", "Kyrgyzstan(+996)");
	    country2phone.put("LA", "Laos(+856)");
	    country2phone.put("LV", "Latvia(+371)");
	    country2phone.put("LB", "Lebanon(+961)");
	    country2phone.put("LS", "Lesotho(+266)");
	    country2phone.put("LR", "Liberia(+231)");
	    country2phone.put("LY", "Libya(+218)");
	    country2phone.put("LI", "Liechtenstein(+423)");
	    country2phone.put("LT", "Lithuania(+370)");
	    country2phone.put("LU", "Luxembourg(+352)");
	    country2phone.put("MK", "Macedonia(+389)");
	    country2phone.put("MG", "Madagascar(+261)");
	    country2phone.put("MW", "Malawi(+265)");
	    country2phone.put("MY", "Malaysia(+60)");
	    country2phone.put("MV", "Maldives(+960)");
	    country2phone.put("ML", "Mali(+223)");
	    country2phone.put("MT", "Malta(+356)");
	    country2phone.put("MH", "MarshallIslands(+692)");
	    country2phone.put("MR", "Mauritania(+222)");
	    country2phone.put("MU", "Mauritius(+230)");
	    country2phone.put("MX", "Mexico(+52)");
	    country2phone.put("FM", "Micronesia(+691)");
	    country2phone.put("MD", "Moldova(+373)");
	    country2phone.put("MC", "Monaco(+377)");
	    country2phone.put("MN", "Mongolia(+976)");
	    country2phone.put("ME", "Montenegro(+382)");
	    country2phone.put("MA", "Morocco(+212)");
	    country2phone.put("MZ", "Mozambique(+258)");
	    country2phone.put("MM", "Myanmar(+95)");
	    country2phone.put("NA", "Namibia(+264)");
	    country2phone.put("NR", "Nauru(+674)");
	    country2phone.put("NP", "Nepal(+977)");
	    country2phone.put("NL", "Netherlands(+31)");
	    country2phone.put("NZ", "NewZealand(+64)");
	    country2phone.put("NI", "Nicaragua(+505)");
	    country2phone.put("NE", "Niger(+227)");
	    country2phone.put("NG", "Nigeria(+234)");
	    country2phone.put("NO", "Norway(+47)");
	    country2phone.put("OM", "Oman(+968)");
	    country2phone.put("PK", "Pakistan(+92)");
	    country2phone.put("PW", "Palau(+680)");
	    country2phone.put("PA", "Panama(+507)");
	    country2phone.put("PG", "PapuaNewGuinea(+675)");
	    country2phone.put("PY", "Paraguay(+595)");
	    country2phone.put("PE", "Peru(+51)");
	    country2phone.put("PH", "Philippines(+63)");
	    country2phone.put("PL", "Poland(+48)");
	    country2phone.put("PT", "Portugal(+351)");
	    country2phone.put("QA", "Qatar(+974)");
	    country2phone.put("RO", "Romania(+40)");
	    country2phone.put("RU", "Russia(+7)");
	    country2phone.put("RW", "Rwanda(+250)");
	    country2phone.put("KN", "SaintKitts(+1-869)");
	    country2phone.put("LC", "SaintLucia(+1-758)");
	    country2phone.put("VC", "SaintVincent(+1-784)");
	    country2phone.put("WS", "Samoa(+685)");
	    country2phone.put("SM", "San Marino(+378)");
	    country2phone.put("ST", "SaoTome(+239)");
	    country2phone.put("SA", "SaudiArabia(+966)");
	    country2phone.put("SN", "Senegal(+221)");
	    country2phone.put("RS", "Serbia(+381)");
	    country2phone.put("SC", "Seychelles(+248)");
	    country2phone.put("SL", "Sierra Leone(+232)");
	    country2phone.put("SG", "Singapore(+65)");
	    country2phone.put("SK", "Slovakia(+421)");
	    country2phone.put("SI", "Slovenia(+386)");
	    country2phone.put("SB", "SolomonIslands(+677)");
	    country2phone.put("SO", "Somalia(+252)");
	    country2phone.put("ZA", "SouthAfrica(+27)");
	    country2phone.put("ES", "Spain(+34)");
	    country2phone.put("LK", "Sri Lanka(+94)");
	    country2phone.put("SD", "Sudan(+249)");
	    country2phone.put("SR", "Suriname(+597)");
	    country2phone.put("SZ", "Swaziland(+268)");
	    country2phone.put("SE", "Sweden(+46)");
	    country2phone.put("CH", "Switzerland(+41)");
	    country2phone.put("SY", "Syria(+963)");
	    country2phone.put("TJ", "Tajikistan(+992)");
	    country2phone.put("TZ", "Tanzania(+255)");
	    country2phone.put("TH", "Thailand(+66)");
	    country2phone.put("TL", "Timor-Leste(+670)");
	    country2phone.put("TG", "Togo(+228)");
	    country2phone.put("TO", "Tonga(+676)");
	    country2phone.put("TT", "TrinidadandTobago(+1-868)");
	    country2phone.put("TN", "Tunisia(+216)");
	    country2phone.put("TR", "Turkey(+90)");
	    country2phone.put("TM", "Turkmenistan(+993)");
	    country2phone.put("TV", "Tuvalu(+688)");
	    country2phone.put("UG", "Uganda(+256)");
	    country2phone.put("UA", "Ukraine(+380)");
	    country2phone.put("AE", "UnitedArabEmirates(+971)");
	    country2phone.put("GB", "United Kingdom(+44)");
	    country2phone.put("US", "United States(+1)");
	    country2phone.put("UY", "Uruguay(+598)");
	    country2phone.put("UZ", "Uzbekistan(+998)");
	    country2phone.put("VU", "Vanuatu(+678)");
	    country2phone.put("VA", "Vatican City(+379)");
	    country2phone.put("VE", "Venezuela(+58)");
	    country2phone.put("VN", "Vietnam(+84)");
	    country2phone.put("YE", "Yemen(+967)");
	    country2phone.put("ZM", "Zambia(+260)");
	    country2phone.put("ZW", "Zimbabwe(+263)");
	    country2phone.put("GE", "Abkhazia(+995)");
	    country2phone.put("TW", "Taiwan(+886)");
	    country2phone.put("AZ", "Nagorno-Karabakh(+374-97)");
	    country2phone.put("CY", "Northern Cyprus(+90-392)");
	    country2phone.put("MD", "Pridnestrovie(+373-533)");
	    country2phone.put("SO", "Somaliland(+252)");
	    country2phone.put("GE", "South Ossetia(+995)");
	    country2phone.put("CX", "ChristmasIsland(+61)");
	    country2phone.put("NF", "NorfolkIsland(+672)");
	    country2phone.put("NC", "New Caledonia(+687)");
	    country2phone.put("PF", "French Polynesia(+689)");
	    country2phone.put("YT", "Mayotte(+262)");
	    country2phone.put("GP", "SaintBarthelemy(+590)");
	    country2phone.put("GP", "SaintMartin(+590)");
	    country2phone.put("PM", "SaintPierre(+508)");
	    country2phone.put("WF", "WallisandFutuna(+681)");
	    country2phone.put("CK", "Cook Islands(+682)");
	    country2phone.put("NU", "Niue(+683)");
	    country2phone.put("TK", "Tokelau(+690)");
	    country2phone.put("GG", "Guernsey(+44)");
	    country2phone.put("IM", "IsleofMan(+44)");
	    country2phone.put("JE", "Jersey(+44)");
	    country2phone.put("AI", "Anguilla(+1-264)");
	    country2phone.put("BM", "Bermuda(+1-441)");
	    country2phone.put("IO", "IndianOcean(+246)");
	    country2phone.put("", "BritishSovereign(+357)");
	    country2phone.put("VG", "BritishVirginIslands(+1-284)");
	    country2phone.put("KY", "CaymanIslands(+1-345)");
	    country2phone.put("FK", "Falkland Islands(+500)");
	    country2phone.put("GI", "Gibraltar(+350)");
	    country2phone.put("MS", "Montserrat(+1-664)");
	    country2phone.put("SH", "SaintHelena(+290)");
	    country2phone.put("TC", "TurksIslands(+1-649)");
	    country2phone.put("MP", "MarianaIslands(+1-670)");
	    country2phone.put("PR", "PuertoRico(+1-787)");
	    country2phone.put("AS", "AmericanSamoa(+1-684)");
	    country2phone.put("GU", "Guam(+1-671)");
	    country2phone.put("VI", "U.S.VirginIslands(+1-340)");
	    country2phone.put("HK", "Hong Kong(+852)");
	    country2phone.put("MO", "Macau(+853)");
	    country2phone.put("FO", "Faroe Islands(+298)");
	    country2phone.put("GL", "Greenland(+299)");
	    country2phone.put("GF", "French Guiana(+594)");
	    country2phone.put("GP", "Guadeloupe(+590)");
	    country2phone.put("MQ", "Martinique(+596)");
	    country2phone.put("RE", "Reunion(+262)");
	    country2phone.put("AX", "Aland(+358-18)");
	    country2phone.put("AW", "Aruba(+297)");
	    country2phone.put("AN", "NetherlandsAntilles(+599)");
	    country2phone.put("SJ", "Svalbard(+47)");
	    country2phone.put("AC", "Ascension(+247)");
	    country2phone.put("TA", "TristandaCunha(+290)");
	    country2phone.put("CS", "Kosovo(+381)");
	    country2phone.put("PS", "PalestinianTerritories(+970)");
	    country2phone.put("EH", "WesternSahara(+212)");
	}
	
	public static String getPhone(String code) {
	    return country2phone.get(code.toUpperCase());
	}
	public static Map<String, String> getAll(){
	    return country2phone;
	}
	public static List<String> getPhoneCountryCodes(){
		List<String> list = new ArrayList<String>(country2phone.values());
		return list;
	}
	
}
