package com.idos.dao.trialbalance;

import com.idos.dao.BaseDAO;
import model.TrialBalance;
import model.Users;
import model.Vendor;

import javax.persistence.EntityManager;
import service.EntityManagerProvider;
import java.util.Date;

/**
 * @author Sunil K Namdev created on 24.11.2019
 *
 */
public interface TrialBalanceVendorCustomerDAO extends BaseDAO {
        String CUSTVEND_ADV_ORG_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE, 0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and  t1.VENDOR_ID=?2 union all select 0 as oob, (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?3 and t2.VENDOR_ID = ?4 and (t2.VENDOR_TYPE= ?5 or t2.VENDOR_TYPE= ?6) and t2.DATE < ?7 union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?8 and t2.VENDOR_ID= ?9 and (t2.VENDOR_TYPE= ?10 or t2.VENDOR_TYPE= ?11) and t2.DATE between ?12 and ?13) tbl group by tbl.vend";

        String CUSTVEND_ADV_ORG_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit, 0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.VENDOR_ID = ?2 union all select 0 as oob, (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?3 and t2.VENDOR_ID = ?4 and (t2.VENDOR_TYPE= ?5 or t2.VENDOR_TYPE= ?6) and t2.DATE < ?7  union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?8 and t2.VENDOR_ID = ?9 and (t2.VENDOR_TYPE= ?10 or t2.VENDOR_TYPE= ?11) and t2.DATE between ?12 and ?13) tbl group by tbl.vend";

        String CUSTVEND_ADV_BRANCH_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit, 0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.BRANCH_ID= ?2 and t1.VENDOR_ID = ?3 union all select 0 as oob, (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?4 and t2.BRANCH_ID=?5 and t2.VENDOR_ID = ?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE < ?9  union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID= ?10 and t2.BRANCH_ID= ?11 and t2.VENDOR_ID = ?12 and (t2.VENDOR_TYPE=?13 or t2.VENDOR_TYPE=?14) and t2.DATE between ?15 and ?16 ) tbl group by tbl.vend";

        String CUSTVEND_ADV_BRANCH_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and t1.BRANCH_ID=?2 and t1.VENDOR_ID = ?3 union all select 0 as oob, (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?4 and t2.BRANCH_ID=?5 and t2.VENDOR_ID = ?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE < ?9  union all  select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?10 and t2.BRANCH_ID=?11 and t2.VENDOR_ID =?12 and (t2.VENDOR_TYPE=?13 or t2.VENDOR_TYPE=?14) and t2.DATE between ?15 and ?16) tbl group by tbl.vend";

        public TrialBalance getTb4CustomerOrVendorAdvance(Users user, EntityManager em, Date fromDate, Date toDate,
                        Long branchId, Vendor vendor);

        String CUSTVEND_ORG_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.VENDOR_ID = ?2 union all select (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?3 and t2.VENDOR_ID = ?4 and (t2.VENDOR_TYPE= ?5 or t2.VENDOR_TYPE= ?6) and t2.DATE < ?7 union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?8 and t2.VENDOR_ID = ?9 and (t2.VENDOR_TYPE= ?10 or t2.VENDOR_TYPE= ?11) and t2.DATE between ?12 and ?13) tbl group by tbl.vend";

        String CUSTVEND_ORG_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.VENDOR_ID = ?2 union all select (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?3 and t2.VENDOR_ID = ?4 and (t2.VENDOR_TYPE= ?5 or t2.VENDOR_TYPE= ?6) and t2.DATE < ?7  union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?8 and t2.VENDOR_ID = ?9 and (t2.VENDOR_TYPE= ?10 or t2.VENDOR_TYPE= ?11) and t2.DATE between ?12 and ?13) tbl group by tbl.vend";

        String CUSTVEND_BRANCH_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.BRANCH_ID= ?2 and t1.VENDOR_ID = ?3 union all select (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?4 and t2.BRANCH_ID= ?5  and t2.VENDOR_ID = ?6 and (t2.VENDOR_TYPE= ?7 or t2.VENDOR_TYPE= ?8) and t2.DATE < ?9 union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?10 and t2.BRANCH_ID= ?11 and t2.VENDOR_ID = ?12 and (t2.VENDOR_TYPE= ?13 or t2.VENDOR_TYPE= ?14) and t2.DATE between ?15 and ?16 ) tbl group by tbl.vend";

        String CUSTVEND_BRANCH_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID= ?1 and t1.BRANCH_ID= ?2 and t1.VENDOR_ID = ?3 union all select (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?4 and t2.BRANCH_ID= ?5 and t2.VENDOR_ID = ?6 and (t2.VENDOR_TYPE= ?7 or t2.VENDOR_TYPE= ?8) and t2.DATE < ?9 union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID= ?10 and t2.BRANCH_ID= ?11 and t2.VENDOR_ID = ?12 and (t2.VENDOR_TYPE= ?13 or t2.VENDOR_TYPE= ?14) and t2.DATE between ?15 and ?16) tbl group by tbl.vend";

        public TrialBalance getTb4CustomerOrVendor(Users user, EntityManager em, Date fromDate, Date toDate,
                        Long branchId,
                        Vendor vendor);
}
