package com.idos.dao;

import model.Users;
import com.fasterxml.jackson.databind.node.ArrayNode;

import javax.persistence.EntityManager;
import service.EntityManagerProvider;
import java.math.BigInteger;
import java.util.List;

/**
 * @auther Sunil Namdev created on 25.12.2018
 */
public interface TransactionViewDAO extends BaseDAO {

    String TXN_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from TRANSACTION where TRANSACTION_BRANCH_ORGANIZATION=?1 and PRESENT_STATUS=1";
    String PJE_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from PROVISION_JOURNAL_ENTRY where BRANCH_ORGANIZATION=?1 and PRESENT_STATUS=1";
    String PAY_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from PAYROLL_TRANSACTION where ORGANIZATION_ID=?1 and PRESENT_STATUS=1";
    String BOM_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from BILL_OF_MATERIAL_TXN where ORGANIZATION_ID=?1 and PRESENT_STATUS=1";
    String PURREQ_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from PURCHASE_REQUISITION_TXN where ORGANIZATION_ID=?1 and PRESENT_STATUS=1";
    String PURORD_JPQL = "select ID, TRANSACTION_PURPOSE, CREATED_AT from PURCHASE_ORDER_TXN where ORGANIZATION_ID=?1 and PRESENT_STATUS=1";

    String MAIN_JPQL = "SELECT ID, TRANSACTION_PURPOSE, CREATED_AT, CREATED_BY, MODIFIED_AT, MODIFIED_BY, PRESENT_STATUS, TRANSACTION_REF_NUMBER, APPROVER_EMAILS, ADDITIONAL_APPROVER_USER_EMAILS, SELECTED_ADDITIONAL_APPROVER, TRANSACTION_STATUS, APPROVER_ACTION_BY, INSTRUMENT_NUMBER, INSTRUMENT_DATE, REMARKS, ";

    String PJE_PRE_MAIN = "BRANCH_ORGANIZATION as org, DEBIT_BRANCH as branch, TRANSACTION_DATE as txndate, SUPPORTING_DOCUMENTS as docs, ";

    String PJE_MAIN = "CREDIT_BRANCH as cbranch, TOTAL_DEBIT_AMOUNT as tdAmt, TOTAL_CREDIT_AMOUNT as tcAmt,  ALLOWED_REVERSAL as reversal, REVERSAL_DATE as rdate, DEBIT_INCOMES_EFFECT as diEffect, DEBIT_EXPENSES_EFFECT as deEffect, DEBIT_ASSETS_EFFECT as daEffect, DEBIT_LIABILITIES_EFFECT as dlEffect, CREDIT_INCOMES_EFFECT as ciEffect, CREDIT_EXPENSE_EFFECT as ceEffect, CREDIT_LABILITIES_EFFECT as clEffect,  CREDIT_ASSETS_EFFECT as caEffect, PROVISION_TYPE as ptype, REVERSAL_STATUS as rstatus,";

    String PJE_TMP = "null as cbranch, null as tdAmt, null as tcAmt,  null as reversal, null as rdate, null as diEffect, null as deEffect, null as daEffect, null as dlEffect, null as ciEffect, null as ceEffect, null as clEffect,  null as caEffect, null as ptype, null as rstatus,";

    String TXN_TMP = "null as bank, null as project, null as specifics, null as particular, null as cusven, null as vcusven, null as units, null as price, null as gross, null as adv, null as aadv, null as dis, null as net, null as descr, null as rtype ,  null as rdesc,  null as disper, null as kstatus, null as txnlimitdesc, null as budget, null as avbudget, null as done, null as pstatus, null as cdue, null as cpayment, null as vdue, null as vpayment, null as apurpose, null as salesReturnAmt, null as purReturnAmt, null as paidInvRef, null as  aremarks, null as procstatus, null as procured, null as vdate, null as taxn1, null as tax1, null as taxn2, null as tax2, null as taxn3, null as tax3, null as taxn4, null as tax4, null as taxn5, null as tax5, null as taxn6, null as tax6, null as taxn7, null as tax7, null as tds, null as cvAccept, null as ebudget, null as asaa, null as afsaa, null as vcRemarks, null as vcDocUrl, null as pmps, null as sitf, null as docRule, null as ptxnrule, null as tobank, null as tobranch, null as corg, null as itfBranch, null as itfOrg, null as asfBranch, null as stiProgress, null as astBranch, null as rstock, null as pInvoice, null  as poref, null as frieght, null as advType, null as brsbDate, null as rconAmt, null as rprivate, null as invNumber, null as sgstin, null as dgstin, null as tos, null as wcType, null as wwTax, null as ltRef, null as typeIden, null as cIncDec, null as isback, null as invValue,";

    String TXN_TMP2 = " null as project, null as specifics, null as particular, null as cusven, null as vcusven, null as units, null as price, null as gross, null as adv, null as aadv, null as dis, null as net, null as descr, null as rtype ,  null as rdesc,  null as disper, null as kstatus, null as txnlimitdesc, null as budget, null as avbudget, null as done, null as pstatus, null as cdue, null as cpayment, null as vdue, null as vpayment, null as apurpose, null as salesReturnAmt, null as purReturnAmt, null as paidInvRef, null as  aremarks, null as procstatus, null as procured, null as vdate, null as taxn1, null as tax1, null as taxn2, null as tax2, null as taxn3, null as tax3, null as taxn4, null as tax4, null as taxn5, null as tax5, null as taxn6, null as tax6, null as taxn7, null as tax7, null as tds, null as cvAccept, null as ebudget, null as asaa, null as afsaa, null as vcRemarks, null as vcDocUrl, null as pmps, null as sitf, null as docRule, null as ptxnrule, null as tobank, null as tobranch, null as corg, null as itfBranch, null as itfOrg, null as asfBranch, null as stiProgress, null as astBranch, null as rstock, null as pInvoice, null  as poref, null as frieght, null as advType, null as brsbDate, null as rconAmt, null as rprivate, null as invNumber, null as sgstin, null as dgstin, null as tos, null as wcType, null as wwTax, null as ltRef, null as typeIden, null as cIncDec, null as isback, null as invValue,";

    String TXN_MAIN = "TRANSACTION_BRANCH_ORGANIZATION as org, TRANSACTION_BRANCH as branch, TRANSACTION_ACTIONDATE as txndate, SUPPORTING_DOCS as docs, TRANSACTION_BRANCH_BANK as bank, TRANSACTION_PROJECT as project, TRANSACTION_SPECIFICS as specifics, TRANSACTION_SPECIFICS_PARTICULARS as particular, TRANSACTION_VENDOR_CUSTOMER as cusven, TRANSACTION_UNAVAILABLE_VENDOR_CUSTOMER as vcusven, NO_OF_UNITS as units, PRICE_PER_UNIT as price, GROSS_AMOUNT as gross, AVAILABLE_ADVANCE as adv, ADJUSTMENT_FROM_ADVANCE as aadv, AVAILABLE_DISCOUNT as dis, NET_AMOUNT as net, NET_AMOUNT_RESULT_DESCRIPTION as descr, RECEIPT_DETAILS_TYPE as rtype ,  RECEIPT_DETAILS_DESCRIPTION as rdesc,  AVAILABLE_DISCOUNT_PERCENTAGE as disper, KLFOLLOWSTATUS as kstatus, USER_TXN_LIMIT_DESCRIPTION as txnlimitdesc, ACTUAL_ALLOCATED_BUDGET as budget, BUDGET_AVAILABLE_DURING_TXN as avbudget, TRANSACTION_DONE as done, PAYMENT_STATUS as pstatus, CUSTOMER_DUE_PAYMENT as cdue, CUSTOMER_NET_PAYMENT as cpayment, VENDOR_DUE_PAYMENT as vdue, VENDOR_NET_PAYMENT as vpayment, ADVANCE_PURPOSE as apurpose, SALES_RETURN_AMOUNT as salesReturnAmt, PURCHASE_RETURN_AMOUNT as purReturnAmt, PAID_INVOICE_REF_NUMBER as paidInvRef, AUDITOR_USER_REMARKS_DATE as  aremarks, PROCUREMENT_STATUS as procstatus, PROCURED_BY as procured, TRANSACTION_INVOICE_DATE as vdate, TAX_NAME_1 as taxn1, TAX_VALUE_1 as tax1, TAX_NAME_2 as taxn2, TAX_VALUE_2 as tax2, TAX_NAME_3 as taxn3, TAX_VALUE_3 as tax3, TAX_NAME_4 as taxn4, TAX_VALUE_4 as tax4, TAX_NAME_5 as taxn5, TAX_VALUE_5 as tax5, TAX_NAME_6 as taxn6, TAX_VALUE_6 as tax6, TAX_NAME_7 as taxn7, TAX_VALUE_7 as tax7, WITHHOLDING_TAX as tds, VENDOR_CUSTOMER_ACCEPTENCE as cvAccept, TRANSACTION_EXCEEDING_BUDGET as ebudget, AVAILABLE_SPECIAL_ADJUSTMENT_AMOUNT as asaa, ADJUSTMENT_FROM_SPECIAL_ADJUSTMENT_AMOUNT as afsaa, VENDOR_CUSTOMER_REMARKS as vcRemarks, VENDOR_CUSTOMER_DOC_URL as vcDocUrl, PAY_MODE_PRESENT_STATUS as pmps, SALES_INDIVIDUAL_TAX_FORMULA as sitf, DOC_RULE_STATUS as docRule, PRESENT_TXN_RULES as ptxnrule, TRANSACTION_TO_BRANCH_BANK as tobank, TRANSACTION_TO_BRANCH as tobranch, TRANSACTION_TO_BRANCH_ORGANIZATION as corg, INVENTORY_TRANSFER_FROM_BRANCH as itfBranch, INVENTORY_TRANSFER_FROM_BRANCH_ORGANIZATION as itfOrg, AVAILABLE_STOCK_FROM_BRANCH as asfBranch, STOCK_TRANSFER_IN_PROGRESS as stiProgress, AVAILABLE_STOCK_TO_BRANCH as astBranch, RESULTANT_STOCK as rstock, PERFORMA_INVOICE as pInvoice, PO_REFERENCE  as poref, FRIEGHT_CHARGES as frieght, advance_type as advType, BRS_BANK_DATE as brsbDate, ROUNDED_CUTPART_OF_NET_AMOUNT as rconAmt, REMARKS_PRIVATE as rprivate, INVOICE_NUMBER as invNumber, SOURCE_GSTIN as sgstin, DESTINATION_GSTIN as dgstin, TYPE_OF_SUPPLY as tos, WALKIN_CUSTOMER_TYPE as wcType, WITH_WITHOUT_TAX as wwTax, LINKED_TXN_REF as ltRef, TYPE_IDENTIFIER as typeIden, CDTDBT_INCREASE_DECREASE as cIncDec, IS_BACKDATED_TRANSACTION as isback, INVOICE_VALUE as invValue, ";

    String PAY_MAIN = " ORGANIZATION_ID as org, BRANCH_ID as branch, TRANSACTION_ACTIONDATE as txndate, SUPPORTING_DOCS as docs, TRANSACTION_BRANCH_BANK as bank, ";

    String PAY_MAIN2 = "PAYSLIP_YEAR as payslipyy, PAYSLIP_MONTH as payslipmm, TOTAL_EARNING1 as tearn1, TOTAL_EARNING2 as tearn2, TOTAL_EARNING3 as tearn3, TOTAL_EARNING4 as tearn4, TOTAL_EARNING5 as tearn5, TOTAL_EARNING6 as tearn6, TOTAL_EARNING7 as tearn7, TOTAL_DEDUCTION1 as tded1, TOTAL_DEDUCTION2 as tded2, TOTAL_DEDUCTION3 as tded3, TOTAL_DEDUCTION4 as tded4, TOTAL_DEDUCTION5 as tded5, TOTAL_DEDUCTION6 as tded6, TOTAL_DEDUCTION7 as tded7, TOTAL_TOTAL_INCOME as ttincome, TOTAL_TOTAL_DEDUCTION as tded, TOTAL_NET_PAY as netpay, ELIGIBLE_DAYS as edays, PAY_DAYS as pdays, PAY_MODE as pmode, EARNING1_ID as earn1id, EARNING2_ID as earn2id, EARNING3_ID as earn3id, EARNING4_ID as earn4id, EARNING5_ID as earn5id, EARNING6_ID as earn6id, EARNING7_ID as earn7id, DEDUCTION1_ID as ded1id, DEDUCTION2_ID as ded2id, DEDUCTION3_ID as ded3id, DEDUCTION4_ID as ded4id, DEDUCTION5_ID as ded5id, DEDUCTION6_ID as ded6id, DEDUCTION7_ID as ded7id";

    String PAY_TMP = "null as payslipyy, null as payslipmm, null as tearn1, null as tearn2, null as tearn3, null as tearn4, null as tearn5, null as tearn6, null as tearn7, null as tded1, null as tded2, null as tded3, null as tded4, null as tded5, null as tded6, null as tded7, null as ttincome, null as tded, null as netpay, null as edays, null as pdays, null as pmode, null as earn1id, null as earn2id, null as earn3id, null as earn4id, null as earn5id, null as earn6id, null as earn7id, null as ded1id, null as ded2id, null as ded3id, null as ded4id, null as ded5id, null as ded6id, null as ded7id";

    BigInteger getTrnsactionsList(Users user, ArrayNode recordArrNodes, EntityManager em, int fromRec, int maxRecord);

    List<Object[]> getAccountingList(long id, long purposeId, EntityManager entityManager);
}
