package com.idos.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.persistence.EntityManager;
import service.EntityManagerProvider;
import javax.persistence.EntityTransaction;

import com.idos.util.IDOSException;
import model.*;

import java.util.logging.Logger;
import java.util.logging.Level;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import service.*;
// import play.Application;
import com.typesafe.config.Config;

public interface TrialBalanceDAO extends BaseDAO {
	// DynamicReportService dynReportService = new DynamicReportServiceImpl();
	// ExceptionService expService = new ExceptionServiceImpl(config);

	String TDS_ORG_SQL8 = "select sum(obalance), sum(credit), sum(debit), sid from( select OPENING_BALANCE as obalance, 0 as credit, 0 as debit, ID as sid from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID =?2 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1 JOIN SPECIFICS t2 ON BRANCH_ORGNIZATION_ID=ORGANIZATION_ID WHERE BRANCH_ORGNIZATION_ID=?3 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID=?4 and tax_type=?5 and DATE < ?6 group by sid union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1 JOIN SPECIFICS t2 ON BRANCH_ORGNIZATION_ID=ORGANIZATION_ID where BRANCH_ORGNIZATION_ID=?7 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID=?8 and tax_type=?9 and DATE between ?10 and ?11 group by sid ) as tbl group by sid";

	String TDS_BRANCH_SQL8 = "select sum(obalance), sum(credit), sum(debit), sid from (select t2.OPENING_BALANCE as obalance, 0 as credit, 0 as debit, t1.ID as sid from SPECIFICS t1 join BRANCH_has_SPECIFICS t2 on t1.ORGANIZATION_ID = t2.BRANCH_ORGANIZATION_ID where t1.ORGANIZATION_ID = ?1 and t2.BRANCH_ID = ?2 and t1.ID = t2.SPECIFICS_ID and t1.IDENT_DATA_VALID = ?3 union all select sum(CREDIT_AMOUNT - DEBIT_AMOUNT) as obalance, 0 as credit, 0 as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1 join SPECIFICS t2 on BRANCH_ORGNIZATION_ID = ORGANIZATION_ID where BRANCH_ORGNIZATION_ID = ?4 and t1.BRANCH_ID = ?5 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID = ?6 and tax_type = ?7 and DATE < ?8 group by BRANCH_TAXESID, sid union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1 join SPECIFICS t2 on BRANCH_ORGNIZATION_ID = ORGANIZATION_ID where BRANCH_ORGNIZATION_ID = ?9 and t1.BRANCH_ID = ?10 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID = ?11 and tax_type = ?12 and DATE between ?13 and ?14 group by BRANCH_TAXESID, sid) as tbl group by sid";

	String TDS_BRANCH_SQL9 = "SELECT SUM(obalance) AS obalance, SUM(credit) AS credit, SUM(debit) AS debit, sid FROM (SELECT t1.ID AS sid, t2.OPENING_BALANCE AS obalance, 0 AS credit, 0 AS debit FROM SPECIFICS t1 INNER JOIN BRANCH_has_SPECIFICS t2 ON t1.ID = t2.SPECIFICS_ID WHERE t1.ORGANIZATION_ID = t2.BRANCH_ORGANIZATION_ID AND t1.ORGANIZATION_ID = ?1 AND t2.BRANCH_ID = ?2 AND t1.ID = t2.SPECIFICS_ID AND t1.IDENT_DATA_VALID = ?3 GROUP BY t1.ID, t2.OPENING_BALANCE UNION ALL SELECT t2.ID AS sid, SUM(CREDIT_AMOUNT - DEBIT_AMOUNT) AS obalance, 0 AS credit, 0 AS debit FROM TRIALBALANCE_TAXES t1 INNER JOIN SPECIFICS t2 ON t1.BRANCH_TAXESID = t2.ID WHERE t1.BRANCH_ORGNIZATION_ID = ORGANIZATION_ID AND t1.BRANCH_ORGNIZATION_ID = ?4 AND t1.BRANCH_ID = ?5 AND t2.IDENT_DATA_VALID = ?6 AND tax_type = ?7 AND DATE < ?8 GROUP BY t2.ID UNION ALL SELECT t2.ID AS sid, 0 AS obalance, SUM(CREDIT_AMOUNT) AS credit, SUM(DEBIT_AMOUNT) AS debit FROM TRIALBALANCE_TAXES t1 INNER JOIN SPECIFICS t2 ON t1.BRANCH_TAXESID = t2.ID WHERE t1.BRANCH_ORGNIZATION_ID = ORGANIZATION_ID AND t1.BRANCH_ORGNIZATION_ID = ?9 AND t1.BRANCH_ID = ?10 AND t2.IDENT_DATA_VALID = ?11 AND tax_type = ?12 AND DATE BETWEEN ?13 AND ?14 GROUP BY t2.ID) AS tbl GROUP BY sid";

	String TDS_ORG_SQL9 = "select sum(obalance), sum(credit), sum(debit), sid from( select OPENING_BALANCE as obalance, 0 as credit, 0 as debit, ID as sid from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID =?2 union all select (sum(CREDIT_AMOUNT) - sum(DEBIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1, SPECIFICS t2 where BRANCH_ORGNIZATION_ID=ORGANIZATION_ID and BRANCH_ORGNIZATION_ID=?3 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID=?4 and tax_type=?5 and DATE < ?6 group by sid union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, BRANCH_TAXESID as sid from TRIALBALANCE_TAXES t1, SPECIFICS t2 where BRANCH_ORGNIZATION_ID=ORGANIZATION_ID and BRANCH_ORGNIZATION_ID=?7 and BRANCH_TAXESID = t2.ID and t2.IDENT_DATA_VALID=?8 and tax_type=?9 and DATE between ?10 and ?11 group by sid ) as tbl group by sid";

	String TAX_BRANCH_JPQL = "select sum(a.openingBalance) from BranchTaxes a where a.organization.id=?1 and a.branch.id=?2 and a.taxType=?3";

	String TAX_ORG_JPQL = "select sum(a.openingBalance) from BranchTaxes a where a.organization.id=?1 and a.taxType=?2";

	String CUSTVEND_ADV_ORG_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE, 0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 group by t1.VENDOR_ID union all select 0 as oob, (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?2 and (t2.VENDOR_TYPE=?3 or t2.VENDOR_TYPE=?4) and t2.DATE < ?5 group by t2.VENDOR_ID union all  select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE between ?9 and ?10 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_ADV_ORG_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 group by t1.VENDOR_ID union all select 0 as oob, (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?2 and (t2.VENDOR_TYPE=?3 or t2.VENDOR_TYPE=?4) and t2.DATE < ?5 group by t2.VENDOR_ID union all  select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE between ?9 and ?10 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_ADV_BRANCH_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and t1.BRANCH_ID=?2 group by t1.VENDOR_ID union all select 0 as oob, (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?3 and t2.BRANCH_ID=?4 and (t2.VENDOR_TYPE=?5 or t2.VENDOR_TYPE=?6) and t2.DATE < ?7 group by t2.VENDOR_ID union all  select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?8 and t2.BRANCH_ID=?9 and (t2.VENDOR_TYPE=?10 or t2.VENDOR_TYPE=?11) and t2.DATE between ?12 and ?13 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_ADV_BRANCH_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and t1.BRANCH_ID=?2 group by t1.VENDOR_ID union all select 0 as oob, (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?3 and t2.BRANCH_ID=?4 and (t2.VENDOR_TYPE=?5 or t2.VENDOR_TYPE=?6) and t2.DATE < ?7 group by t2.VENDOR_ID union all  select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_ADVANCE t2 where t2.BRANCH_ORGNIZATION_ID=?8 and t2.BRANCH_ID=?9 and (t2.VENDOR_TYPE=?10 or t2.VENDOR_TYPE=?11) and t2.DATE between ?12 and ?13 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_ORG_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 group by t1.VENDOR_ID union all select (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?2 and (t2.VENDOR_TYPE=?3 or t2.VENDOR_TYPE=?4) and t2.DATE < ?5 group by t2.VENDOR_ID union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE between ?9 and ?10 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_ORG_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 group by t1.VENDOR_ID union all select (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?2 and (t2.VENDOR_TYPE=?3 or t2.VENDOR_TYPE=?4) and t2.DATE < ?5 group by t2.VENDOR_ID union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?6 and (t2.VENDOR_TYPE=?7 or t2.VENDOR_TYPE=?8) and t2.DATE between ?9 and ?10 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_BRANCH_JPQL_AST = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and t1.BRANCH_ID=?2 group by t1.VENDOR_ID union all select (sum(ifnull(t2.DEBIT_AMOUNT,0))-sum(ifnull(t2.CREDIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?3 and t2.BRANCH_ID=?4 and (t2.VENDOR_TYPE=?5 or t2.VENDOR_TYPE=?6) and t2.DATE < ?7 group by t2.VENDOR_ID union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?8 and t2.BRANCH_ID=?9 and (t2.VENDOR_TYPE=?10 or t2.VENDOR_TYPE=?11) and t2.DATE between ?12 and ?13 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String CUSTVEND_BRANCH_JPQL_LIB = "select sum(oob), sum(ooba), sum(credit), sum(debit), vend from ( select sum(ifnull(t1.ORIGINAL_OPENING_BALANCE,0)) as oob, sum(ifnull(t1.ORIGINAL_OPENING_BALANCE_ADVANCEPAID,0)) as ooba, 0 as credit,  0 as debit, t1.VENDOR_ID as vend from BRANCH_has_VENDORS t1 where t1.BRANCH_ORGANIZATION_ID=?1 and t1.BRANCH_ID= ?2 group by t1.VENDOR_ID union all select (sum(ifnull(t2.CREDIT_AMOUNT,0))-sum(ifnull(t2.DEBIT_AMOUNT,0))) as oob, 0 as ooba, 0 as credit, 0 as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?3 and t2.BRANCH_ID=?4 and (t2.VENDOR_TYPE=?5 or t2.VENDOR_TYPE=?6) and t2.DATE < ?7 group by t2.VENDOR_ID union all select 0 as oob, 0 as ooba, sum(ifnull(t2.CREDIT_AMOUNT,0)) as credit, sum(ifnull(t2.DEBIT_AMOUNT,0)) as debit, t2.VENDOR_ID as vend from TRIALBALANCE_VENDOR_CUSTOMER t2 where t2.BRANCH_ORGNIZATION_ID=?8 and t2.BRANCH_ID=?9 and (t2.VENDOR_TYPE=?10 or t2.VENDOR_TYPE=?11) and t2.DATE between ?12 and ?13 group by t2.VENDOR_ID) tbl group by tbl.vend";

	String USER_ADV_EXP_TRAV_ORG_TOTAL_JPQL = "select sum(obalance), sum(credit), sum(debit) from(select OPENING_BALANCE as obalance, 0 as credit, 0 as debit from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID = ?3 and t1.DATE < ?4 and t1.PRESENT_STATUS=1 union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID = ?5 and t1.DATE between ?6 and ?7 and t1.PRESENT_STATUS=1) tbl";
	String USER_ADV_EXP_TRAV_BRNCH_TOTAL_JPQL = "select sum(obalance), sum(credit), sum(debit) from(select OPENING_BALANCE as obalance, 0 as credit, 0 as debit from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID = ?3 and t1.BRANCH_ID = ?4 and t1.DATE < ?5 and t1.PRESENT_STATUS=1 union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID = ?6 and t1.BRANCH_ID = ?7 and t1.DATE between ?8 and ?9 and t1.PRESENT_STATUS=1) tbl";
	String USER_ADV_EXP_TRAV_ORG_JPQL = "select sum(obalance), sum(credit), sum(debit), name, uid from(select OPENING_BALANCE_ADV as obalance, 0 as credit, 0 as debit, FULL_NAME as name, ID as uid from USERS where BRANCH_ORGANIZATION_ID = ?1 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, null as name, t1.USER_ID as uid  from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID= ?2 and  t1.DATE < ?3 and t1.PRESENT_STATUS=1 group by t1.USER_ID union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, null as name, t1.USER_ID as uid from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID= ?4 and t1.DATE between ?5 and ?6 and t1.PRESENT_STATUS=1 group by t1.USER_ID) tbl group by uid";
	String USER_ADV_EXP_TRAV_BRNH_JPQL = "select sum(obalance), sum(credit), sum(debit), name, uid from(select OPENING_BALANCE_ADV as obalance, 0 as credit, 0 as debit, FULL_NAME as name, ID as uid from USERS where BRANCH_ORGANIZATION_ID = ?1 and BRANCH_ID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, null as name, t1.USER_ID as uid  from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID= ?3 and t1.BRANCH_ID = ?4 and t1.DATE < ?5 and t1.PRESENT_STATUS=1 group by t1.USER_ID union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, null as name, t1.USER_ID as uid from TRIALBALANCE_USER_ADVANCE t1 where t1.BRANCH_ORGNIZATION_ID= ?6 and t1.BRANCH_ID = ?7 and t1.DATE between ?8 and ?9 and t1.PRESENT_STATUS=1 group by t1.USER_ID) tbl group by uid";

	String EMP_CLAIM_ORG_TOTAL_JPQL = "select sum(obalance), sum(credit), sum(debit) from(select OPENING_BALANCE as obalance, 0 as credit, 0 as debit from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID = ?3 and t1.DATE < ?4 and t1.PRESENT_STATUS=1 union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID = ?5 and t1.DATE between ?6 and ?7 and t1.PRESENT_STATUS=1) tbl";
	String EMP_CLAIM_BRNCH_TOTAL_JPQL = "select sum(obalance), sum(credit), sum(debit) from(select OPENING_BALANCE as obalance, 0 as credit, 0 as debit from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID = ?3 and t1.BRANCH_ID = ?4 and t1.DATE < ?5 and t1.PRESENT_STATUS=1 union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID = ?6 and t1.BRANCH_ID = ?7 and t1.DATE between ?8 and ?9 and t1.PRESENT_STATUS=1) tbl";

	String EMP_CLAIM_ORG_JPQL = "select sum(obalance), sum(credit), sum(debit), name, uid from(select OPENING_BALANCE_CLAIM as obalance, 0 as credit, 0 as debit, FULL_NAME as name, ID as uid from USERS where BRANCH_ORGANIZATION_ID = ?1 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, null as name, t1.USER_ID as uid  from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID= ?2 and  t1.DATE < ?3 and t1.PRESENT_STATUS=1 group by t1.USER_ID union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, null as name, t1.USER_ID as uid from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID= ?4 and t1.DATE between ?5 and ?6 and t1.PRESENT_STATUS=1 group by t1.USER_ID) tbl group by uid";
	String EMP_CLAIM_BRNH_JPQL = "select sum(obalance), sum(credit), sum(debit), name, uid from(select OPENING_BALANCE_CLAIM as obalance, 0 as credit, 0 as debit, FULL_NAME as name, ID as uid from USERS where BRANCH_ORGANIZATION_ID = ?1 and BRANCH_ID = ?2 and PRESENT_STATUS=1 union all select (sum(DEBIT_AMOUNT) - sum(CREDIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, null as name, t1.USER_ID as uid  from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID = ?3 and t1.BRANCH_ID = ?4 and t1.DATE < ?5 and t1.PRESENT_STATUS=1 group by t1.USER_ID union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, null as name, t1.USER_ID as uid from TRIALBALANCE_USER_CLAIM t1 where t1.ORGNIZATION_ID= ?6 and t1.BRANCH_ID = ?7 and t1.DATE between ?8 and ?9 and t1.PRESENT_STATUS=1 group by t1.USER_ID) tbl group by uid";

	String TB_BRANCH_FOR_TAXES_JPQL = "select obj.branchTaxes.id, obj.branchTaxes.taxName, obj.branch.name, obj.branchTaxes.openingBalance, SUM(obj.creditAmount), SUM(obj.debitAmount) from TrialBalanceTaxes obj where obj.taxType= ?1 and obj.organization.id= ?2 and obj.branch.id = ?3 and obj.date between ?4 and ?5 group by obj.branchTaxes";
	String TB_ORG_FOR_TAXES_JPQL = "select obj.branchTaxes.id, obj.branchTaxes.taxName, obj.branch.name, obj.branchTaxes.openingBalance, SUM(obj.creditAmount), SUM(obj.debitAmount) from TrialBalanceTaxes obj where obj.taxType= ?1 and obj.organization.id= ?2 and obj.date between ?3 and ?4 group by obj.branchTaxes";

	String TB_BRANCH_FOR_TAXES_TOTAL_JPQL = "select SUM(obj.creditAmount), SUM(obj.debitAmount) from TrialBalanceTaxes obj where obj.taxType= ?1  and obj.organization.id= ?2 and obj.branch.id=?3 and obj.date  between ?4 and ?5 group by obj.branchTaxes";
	String TB_ORG_FOR_TAXES_TOTAL_JPQL = "select SUM(obj.creditAmount), SUM(obj.debitAmount) from TrialBalanceTaxes obj where obj.taxType= ?1  and obj.organization.id= ?2 and obj.date  between ?3 and ?4 group by obj.branchTaxes";

	String WITHOUT_TREE_MAPPED_ITEM_TOTAL_ORG_SQL51 = "select sum(obalance), sum(credit), sum(debit), sid from( select OPENING_BALANCE as obalance, 0 as credit, 0 as debit, ID as sid from SPECIFICS where ORGANIZATION_ID = ?1 and IDENT_DATA_VALID = ?2 union all select (sum(CREDIT_AMOUNT) - sum(DEBIT_AMOUNT)) as obalance, 0 as credit, 0 as debit, TRANSACTION_SPECIFICS as sid from TRIALBALANCE_COAITEMS t1 JOIN SPECIFICS t2 on t1.BRANCH_ORGNIZATION_ID=t2.ORGANIZATION_ID where t1.BRANCH_ORGNIZATION_ID= ?3 and t1.TRANSACTION_SPECIFICS = t2.ID and t2.IDENT_DATA_VALID= ?4 and t1.DATE < ?5 group by sid union all select 0 as obalance, sum(CREDIT_AMOUNT) as credit, sum(DEBIT_AMOUNT) as debit, t1.TRANSACTION_SPECIFICS as sid from TRIALBALANCE_COAITEMS t1 JOIN SPECIFICS t2 ON t1.BRANCH_ORGNIZATION_ID=t2.ORGANIZATION_ID where t1.BRANCH_ORGNIZATION_ID= ?6 and t1.TRANSACTION_SPECIFICS = t2.ID and t2.IDENT_DATA_VALID= ?7 and t1.DATE between ?8 and ?9 group by sid ) as tbl group by sid";

	String WITHOUT_TREE_MAPPED_ITEM_TOTAL_BRANCH_SQL51 = "SELECT SUM(obalance), SUM(credit), SUM(debit), sid FROM ( SELECT OPENING_BALANCE AS obalance, 0 AS credit, 0 AS debit, ID AS sid FROM SPECIFICS WHERE ORGANIZATION_ID = ?1 AND IDENT_DATA_VALID = ?2 UNION ALL SELECT (SUM(CREDIT_AMOUNT) - SUM(DEBIT_AMOUNT)) AS obalance, 0 AS credit, 0 AS debit, TRANSACTION_SPECIFICS AS sid FROM TRIALBALANCE_COAITEMS t1 JOIN SPECIFICS t2 ON t1.BRANCH_ORGNIZATION_ID = t2.ORGANIZATION_ID WHERE t1.BRANCH_ORGNIZATION_ID = ?3 AND t1.BRANCH_ID = ?4 AND t1.TRANSACTION_SPECIFICS = t2.ID AND t2.IDENT_DATA_VALID = ?5 AND t1.DATE < ?6 GROUP BY sid UNION ALL SELECT 0 AS obalance, SUM(CREDIT_AMOUNT) AS credit, SUM(DEBIT_AMOUNT) AS debit, t1.TRANSACTION_SPECIFICS AS sid FROM TRIALBALANCE_COAITEMS t1 JOIN SPECIFICS t2 ON t1.BRANCH_ORGNIZATION_ID = t2.ORGANIZATION_ID WHERE t1.BRANCH_ORGNIZATION_ID = ?7 AND t1.BRANCH_ID = ?8 AND t1.TRANSACTION_SPECIFICS = t2.ID AND t2.IDENT_DATA_VALID = ?9 AND t1.DATE BETWEEN ?10 AND ?11 GROUP BY sid ) AS tbl GROUP BY sid";

	String RESERVE_SURPLUS_JPQL = "select obj from BranchSpecifics as obj where obj.organization.id = ?1 and obj.branch.id = ?2 and obj.specifics.id=?3 and obj.presentStatus=1";

	public String downloadTrialBalance(ObjectNode result, JsonNode json, Users user, EntityManager entityManager,
			String path);

	List<TrialBalance> displayTrialBalance(ObjectNode result, JsonNode json, Users user, EntityManager entityManager)
			throws IDOSException;

	public String exportTrialBalancePDF(String fromDate, String toDate, Users user, Branch branch);

	public Map<String, Object> getParams(final Branch branch, final String fromDate, final String toDate);

	public void getTBForSpecificsTotal(List<Specifics> leafItems, TrialBalance tb, Users user, Specifics itemSpecifics,
			String fromDate, String toDate, Long branchId, EntityManager em, final short particularType);
	// public void getTrialBalanceRoundingOffForSellTranTotal(TrialBalance tb, Users
	// user, String fromDate, String toDate, Specifics specf, Long branchId,
	// EntityManager em,Boolean isJournalEntryIncluded);

	double getTrialBalanceBranchCashTotal(TrialBalance tb, Users user, String fromDate, String toDate,
			Specifics itemSpecifics, short cashType, Long branchId, EntityManager em);

	double getTrialBalanceBranchBankTotal(TrialBalance tb, Users user, String fromDate, String toDate,
			Specifics itemSpecifics, Long branchId, EntityManager em);

	void getTrialBalanceAmountForCOAItem(TrialBalance tb, Users user, Specifics specifics, String fromDate,
			String toDate, Long branchId, EntityManager em, final short incomeOrExpense);

	Double getOpeningBalForSpecifics(String tableName, Double openingBal, Long headID, Users user, String fromDate,
			String columnName, final short particularType, Long branchId, EntityManager em, String headType);

	Double getOpeningBalForTaxes(Users user, String fromDate, Long branchId, EntityManager em, final short taxType,
			Long taxId, Double openingBal, final short particularType);
}
